Extensión, Km<sup>2</sup>: 1932<br>
Altitud, m: (500-1825) 1111<br>
Pendiente, %: (1-15) 7<br>
Términos municipales: Beas de Segura, Benatae, Comunidad de Benatae y Torres de Albanchez (CON. 6123016, 6123091), Comunidad de Benatae y Torres de Albanchez (CON. 6123016, 6123091), Genave, Hornos, Huecos de Bañares, La Puerta de Segura, Orcera, Puente de Genave, San Miguel de Bujaraiza, Santiago-Pontones, Segura de la Sierra, Siles, Torres de Albanchez, Villarodrigo.<br>
