Extensión, Km<sup>2</sup>: 1644<br>
Altitud, m: (680-2721) 1451<br>
Pendiente, %: (1-17) 9<br>
Términos municipales: Alas i Cerc, Arseguel, Bellver de Cerdanya, Cabo, Cava, Cava i El Pont de Bar, Coll de Nargo, El Pont de Bar, Estamariu, Figols i Alinya, Gosol, Josa i Tuixen, La Seu d'Urgell, La Vansa i Fornols, Les Valls d'Aguilar, Les Valls de Valira, Llers de Cerdanya, Montella i Martinet, Montferri i Castellbo, Organya, Prats i Sansor, Prullans, Ribera d'Urgellet, Riu de Cerdanya.<br>
