Extensión, Km<sup>2</sup>: 2101<br>
Altitud, m: (820-2499) 1670<br>
Pendiente, %: (1-20) 10<br>
Términos municipales: Alins, Alt Aneu, Baix Pallars, El Pont de Suert, Espot, Esterri d'Aneu, Esterri d'Aneu i Alt Aneu, Esterri de Cardos, Farrera, La Guingueta  d'Aneu, La Torre de Cabdella, La Vall de Boi, Lladorre, Llavorsi, Rialp, Sarroca de Bellera, Senterada, Soriguera, Sort, Tirvia, Vall de Cardos, Vilaller.<br>
