Extensión, Km<sup>2</sup>: 1078<br>
Altitud, m: (200-701) 396<br>
Pendiente, %: (1-4) 3<br>
Términos municipales: Alcano, Alfes, Almatret, Arberca, Aspa, Bellaguarda, Bovera, Castelldans, Cervia de les Garrigues, El Cogul, El Soleras, El Vilosell, Els Omellons, Els Torms, Fulleda, Granyena de les Garrigues, Juncosa, L'Albages, L'Albi, L'Espluga Calba, La Floresta, La Granadella, La Pobla de Cervoles, Les Borges Blanques, Llardecans, Maials, Puiggros, Sarroca de Lleida, Sunver, Tarres, Torrebesses, Vinaixa.<br>
