Extensión, Km<sup>2</sup>: 1065<br>
Altitud, m: (80-351) 212<br>
Pendiente, %: (1-2) 2<br>
Términos municipales: Aitona, Albatarrec, Alcarras, Alcoletge, Alfarras, Alguaire, Almacelles, Almenar, Alpicat, Artesa de Lleida, Benavente de Segria, Corbins, Els Alamus, Gimenells i el Pla de la Font, La Granja d'Escarp, La Portella, Lleida, Massalcoreig, Montoliu de Lleida, Puigverd de Lleida, Rosello, Seros, Soses, Sudanell, Torre-serona, Torrefarrera, Torres de Segre, Vilanova de Segria, Vilanova de la Barca.<br>
