Extensión, Km<sup>2</sup>: 1748<br>
Altitud, m: (200-1100) 487<br>
Pendiente, %: (1-8) 5<br>
Términos municipales: Ager, Albesa, Algerri, Alos de Balaguer, Artesa de Segre, Balaguer, Bellvis, Cabanabona, Camarasa, Castello de Farfanya, Cubells, Foradada, Isona i Conca Della, Ivars de Noguera, La Baronia de Rialb, La Sentiu de Sio, Les Avellanes i Santa Linya, Menarguens, Montgai, Oliola, Os de Balaguer, Ponts, Temens, Tiurana, Torrelameu, Vallfogona de Balaguer, Vilanova de Meia, Vilanova de l'Aguda.<br>
