Extensión, Km<sup>2</sup>: 741<br>
Altitud, m: (238-397) 300<br>
Pendiente, %: (1-2) 2<br>
Términos municipales: Agramunt, Anglesola, Barbens, Barbens, Bell-lloc d'Urgell, Bellcaire d'Urgell, Bellmunt d'Urgell, Bellpuig, Castellnou de Seana, Castellsera, El Palau d'Anglesola, El Poal, Els Alamus, Fordarella, Golmes, Ivars d'Urgell, Juneda, La Fuliola, Linyola, Miralcamp, Mollerussa, Penelles, Preixana, Preixens, Puigverd d'Agramunt, Sidamon, Tarrega, Tornabous, Torregrossa, Vila-sana, Vilagrassa, Vilanova de Bellpuig.<br>
