Extensión, Km<sup>2</sup>: 972<br>
Altitud, m: (327-620) 493<br>
Pendiente, %: (1-4) 3<br>
Términos municipales: Belianes, Biosca, Cervera, Ciutadilla, Els Omells de na Gaia, Els Plans de Sio, Estaras, Granyanella, Granyena de Segarra, Guimera, Guissona, Ivorra, La Molsosa, Les Oluges, Malda, Massoteres, Montoliu de Segarra, Montornes de Segarra, Nalec, Osso de Sio, Ribera d'Ondara, Sanaüja, Sant Guim de Freixenet, Sant Guim de la Plana, Sant Marti de Riucorb, Sant Ramon, Talavera, Tarroja de Segarra, Tora, Torrefeta i Florejacs, Vallbona de les Monges, Verdu.<br>
