Extensión, Km<sup>2</sup>: 4757<br>
Altitud, m: (415-770) 586<br>
Pendiente, %: (1-5) 3<br>
Términos municipales: Alcaracejos, Añora, Belalcazar, Belmez, Blazquez, Cardeña, Conquista, Dos Torres, El Viso, Fuente Obejuna, Fuente la Lancha, Guijo, Hinojosa del Duque, La Granjuela, Pedroche, Peñarroya-Pueblonuevo, Pozoblanco, Santa Eufemia, Torrecampo, Valsequillo, Villanueva de Cordoba, Villanueva del Duque, Villaralto.<br>
