Precámbrico: Serie pizarroso-detrítica, arcosas y conglomerados arcósicos <br>
Cámbrico: Calcoesquistos, calizas, pizarras, vulcanitas, grauwacas y cuarcitas, conglomerados de matriz volcánica, rocas volcánicas básicas e intermedias, pirocláticas  y arcosas<br>
Carbonífero: Indiferenciado, pizarras mosqueadas y corneanas, calizas y conglomerados<br>
Cuaternario: Limos, cantos, gravas, arenas, costras y cantos rodados<br>
Neógeno: Materiales calcáreos, calizas, areniscas y margas azules<br>
Rocas ácidas: Granito<br>
Rocas volcánicas: Brechas volcánicas<br>
