Extensión, Km<sup>2</sup>: 2242<br>
Altitud, m: (291-1882) 577<br>
Pendiente, %: (1-11) 6<br>
Términos municipales: Aceituna, Aldehuela de Jerte, Arroyomolinos de la Vera, Barrado, Cabezabellosa, Cabezuela del Valle, Cabrero, Carcaboso, Casas del Castañar, El Torno, Galisteo, Gargüera, Jerte, Malpartida de Plasencia, Mirabel, Montehermoso, Navaconejo, Oliva de Plasencia, Pasaron de la Vera, Piornal, Plasencia, Rebollar, Santa Cruz de Paniagua, Santibañez el Bajo, Serradilla, Tejada de Tietar, Tornavacas, Torrejon el Rubio, Torremenga, Valdastillas, Valdeobispo, Villar de Plasencia.<br>
