Extensión, Km<sup>2</sup>: 2319<br>
Altitud, m: (297-776) 478<br>
Pendiente, %: (1-6) 4<br>
Términos municipales: Aldea de Trujillo, Aldeacentenera, Almoharin, Conquista de la Sierra, Escurial, Garziaz, Herguijuela, Ibahernando, Jaraicejo, La Cumbre, Madroñera, Miajadas, Plasenzuela, Puerto de Santa Cruz, Robledillo de Trujillo, Ruanes, Salvatierra de Santiago, Santa Ana, Santa Cruz de la Sierra, Santa Marta de Magasca, Torrecillas de la Tiesa, Trujillo, Villamesias.<br>
