Extensión, Km<sup>2</sup>: 2445<br>
Altitud, m: (250-1105) 426<br>
Pendiente, %: (1-7) 4<br>
Términos municipales: Almaraz, Belvis de Monroy, Berrocalejo, Bohonal de Ibor, Campillo de Deleitosa, Carrascalejo, Casas de Miravete, Casatejada, Castañar de Ibor, Deleitosa, El Gordo, Fresnedoso de Ibor, Garvin, Higuera, Majadas, Mesas de Ibor, Millanes, Navalmoral de la Mata, Navalvillar de Ibor, Peraleda de San Roman, Peraleda de la Mata, Robledollano, Romangordo, Rosalejo, Saucedilla, Serrejon, Talayuela, Toril, Valdecañas de Tajo, Valdehuncar, Valdelacasa de Tajo, Villar del Pedroso.<br>
