Extensión, Km<sup>2</sup>: 2339<br>
Altitud, m: (295-1214) 482<br>
Pendiente, %: (1-8) 5<br>
Términos municipales: Acebo, Cachorilla, Cadalso, Calzadilla, Casas de Don Gomez, Casillas de Coria, Cilleros, Coria, Descargamaria, Eljas, Gata, Guijo de Coria, Guijo de Galisteo, Hernan-Perez, Holguera, Hoyos, Huelaga, Moraleja, Morcillo, Pedroso de Acim, Perales del Puerto, Pescueza, Portaje, Portezuelo, Pozuelo de Zarzon, Riolobos, Robledillo de Gata, San Martin de Trevejo, Santibañez el Alto, Torre de Don Miguel, Torrecilla de los Angeles, Torrejoncillo, Valverde del Fresno, Villa del Campo, Villamiel, Villanueva de la Sierra, Villasbuenas de Gata.<br>
