Extensión, Km<sup>2</sup>: 1165<br>
Altitud, m: (400-1088) 642<br>
Pendiente, %: (1-13) 6<br>
Términos municipales: Abadia, Ahigal, Aldeanueva del Camino, Baños de Montemayor, Caminomorisco, Casar de Palomero, Casares de las Hurdes, Casas del Monte, Cerezo, Gargantilla, Guijo de Granadilla, Hervas, Jarilla, La Garganta, La Granja, La Presga, Ladrillar, Marchagaz, Mohedas de Granadilla, Nuñomoral, Palomero, Pinofranqueado, Segura de Toro, Zarza de Granadilla.<br>
