Extensión, Km<sup>2</sup>: 705<br>
Altitud, m: (303-1910) 945<br>
Pendiente, %: (1-16) 6<br>
Términos municipales: Aldeanueva de la Vera, Collado, Cuacos de Yuste, Garganta de Olla, Guijo de Santa Barbara, Jaraiz de la Vera, Jarandilla de la Vera, Losar de la Vera, Madrigal de la Vera, Robledillo de la Vera, Talaveruela de la Vera, Valverde de la Vera, Viandar de la Vera, Villanueva de la Vera.<br>
