Extensión, Km<sup>2</sup>: 3721<br>
Altitud, m: (300-902) 428<br>
Pendiente, %: (1-9) 4<br>
Términos municipales: Albala del Caudillo, Alcuescar, Aldea del Cano, Aliseda, Arroyo de la Luz, Arroyomolinos de Montanchez, Benquerencia, Botija, Caceres, Casar de Caceres, Casas de Don Antonio, Casas de Millan, Cañaveral, Garrovillas, Hinojal, Malpartida de Caceres, Monroy, Montanchez, Santiago del Campo, Sierra de Fuentes, Talavan, Torre de Santa Maria, Torremocha, Torreorgaz, Torrequemada, Valdefuentes, Valdemorales, Zarza de Montanchez.<br>
