Extensión, Km<sup>2</sup>: 2160<br>
Altitud, m: (400-807) 570<br>
Pendiente, %: (1-6) 4<br>
Términos municipales: Atalaya, Bienvenida, Calera de Leon, Calzadilla de los Barros, Casas de Reina, Fuente de Cantos, Fuente del Arco, Higuera de Llerena, Llerena, Medina de las Torres, Monesterio, Montemollin, Puebla del Maestre, Reina, Trasierra, Usagre, Valencia del Ventoso, Villagarcia de la Torre.<br>
