Extensión, Km<sup>2</sup>: 2146<br>
Altitud, m: (227-763) 460<br>
Pendiente, %: (1-4) 3<br>
Términos municipales: Barcarrota, Bodonal de la Sierra, Burguillos del Cerro, Cabeza la Vaca, Freguenal de la Sierra, Fuentes de Leon, Higuera la Real, Jerez de los Caballeros, Oliva de la Frontera, Salvaleon, Segura de Leon, Valencia del Mombuey, Valle de Matamoros, Valle de Santa Ana, Valverde de Burguillos, Zahinos.<br>
