Extensión, Km<sup>2</sup>: 2136<br>
Altitud, m: (275-700) 437<br>
Pendiente, %: (1-5) 3<br>
Términos municipales: Aceuchal, Alconera, Almendralejo, Feria, Fuente del Maestre, Hinojosa del Valle, Hornachos, La Lapa, La Morera, La Parra, Llera, Los Santos de Maimona, Palomas, Puebla de Sancho Perez, Puebla de la Reina, Puebla del Prior, Ribera del Fresno, Salvatierra de los Barros, Santa Marta, Solana de los Barros, Villafranca de los Barros, Villalba de los Barros, Zafra.<br>
