Extensión, Km<sup>2</sup>: 2052<br>
Altitud, m: (200-500) 294<br>
Pendiente, %: (1-5) 3<br>
Términos municipales: Alange, Aljucen, Arroyo de San Servan, Calamonte, Carmonita, Cordobilla de Lacara, Don Alvaro, El Carrascalejo, Esparragalejo, La Garrovilla, La Nava de Santiago, La Zarza, Lobon, Merida, Mirandilla, Montijo, Oliva de Merida, Puebla de la Calzada, San Pedro de Merida, Torremayor, Torremejia, Trujillanos, Valverde Merida, Villagonzalo.<br>
