Cámbrico: Metamórfico, areniscas, pizarras, vulcanitas al techo, cuarcitas, conglomerados, serie detrítica inferior y serie carbonatada<br>
Neógeno: Indiferenciado, arcillas areniscosas, arcillas, margas, conglomerados y areniscas<br>
Precámbrico: Gneises glandulares, intercolaciones carbonatadas, pizarras, cuarcitas oscuras y vulcanitas básicas<br>
Cuaternario: Derrubios<br>
Rocas ácidas: Anfibolitas, granodioritas y granito con biotita<br>
<br>
