Extensión, Km<sup>2</sup>: 1768<br>
Altitud, m: (897-1294) 1055<br>
Pendiente, %: (1-4) 2<br>
Términos municipales: Aguaton, Alba, Baguena, Barrachina, Bañon, Bello, Blancas, Bueña, Burbaguena, Calamocha, Caminreal, Castejon de Tornos, Cella, Fuentes Claras, Monreal del Campo, Odon, Ojos Negros, Pozuel del Campo, Rubielos de la Cerida, San Martin del Rio, Santa Eulalia, Singra, Tornos, Torralba de los Sisones, Torrelacarcel, Torremocha de Jiloca, Torrijo del Campo, Villafranca del Campo, Villarquemado.<br>
