Extensión, Km<sup>2</sup>: 2782<br>
Altitud, m: (900-1717) 1194<br>
Pendiente, %: (1-9) 4<br>
Términos municipales: Abejuela, Albentosa, Alfambra, Arcos de las Salinas, Argente, Camarena de la Sierra, Camañas, Cascante del Rio, Celadas, Corbalan, Cubla, Cuevas Labradas, Escorihuela, Galve, La Puebla de Valverde, Libros, Lidon, Manzanera, Olba, Orrios, Peralejos, Perales del Alfambra, Riodeva, San Agustin, Sarrion, Teruel, Torrijas, Tramacastiel, Valacloche, Valbona, Villastar, Villel, Visiedo.<br>
