Extensión, Km<sup>2</sup>: 2400<br>
Altitud, m: (979-1806) 1420<br>
Pendiente, %: (1-9) 5<br>
Términos municipales: Ababuj, Aguilar del Alfambra, Alcala de la Selva, Allepuz, Cabra de Mora, Cantavieja, Cañada de Benatanduz, Cedrillas, El Castellar, El Pobo, Formiche Alto, Fortanete, Fuene de Rubielos, Gudar, Jorcas, La Cuba, La Iglesuela del Cid, Linares de Mora, Miramber, Miravete de la Sierra, Monteagudo del Castillo, Mora de Rubielos, Mosqueruela, Nogueruelas, Pitarque, Puertomingalvo, Rubielos de Mora, Tronchon, Valdelinares, Villarluengo, Villaroya de los Pinares.<br>
