Extensión, Km<sup>2</sup>: 1601<br>
Altitud, m: (1099-1720) 1406<br>
Pendiente, %: (1-6) 3<br>
Términos municipales: Albarracin, Almohama, Alobras, Bezas, Broncahles, Calomarde, El Cuervo, El Vallecillo, Frias de Albarracin, Gea de Albarracin, Griegos, Guadalaviar, Jabaloyas, Monterde de Albarracin, Moscardon, Noguera de Albarracin, Orihuela del Tremedal, Peracense, Pozondon, Rodenas, Royuela, Rubiales, Saldon, Terriente, Toril y Masegoso, Tormon, Torres de Albarracin, Tramacastilla, Valdecuenca, Veguillas de la Sierra, Villar del Cobo, Villar del Salz.<br>
