Cuaternario: Brechas, conglomerados, arcillas con cantos, glacis, indiferenciado, arenas, gravas, limos, aluvial y terrazas<br>
Neógeno: Areniscas, margas, arcillas, calizas, yesos, conglomerados y lutitas<br>
Jurásico: Brechas, calizas dolomíticas, calizas, brechas calcareo-dolomíticas y calizas con silex<br>
Cretácico: Indiferenciado<br>
Cámbrico: Cuarcitas, pizarras, areniscas, rocas volcánicas, margas, calizas y dolomías<br>
<br>
