Extensión, Km<sup>2</sup>: 3013<br>
Altitud, m: (200-788) 457<br>
Pendiente, %: (1-7) 4<br>
Términos municipales: Alajar, Almonaster la Real, Aracena, Aroche, Arroyomolinos de Leon, Cala, Castaño del Robledo, Cañaveral de Leon, Corteconcepcion, Cortegana, Cortelazor, Cumbres Mayores, Cumbres de Enmedio, Cumbres de San Bartolome, Encinasola, Fuenteheridos, Galaroza, Higuera de la Sierra, Hinojales, Jabugo, La Nava, Linares de la Sierra, Los Marines, Puerto Moral, Rosal de la Frontera, Santa Ana la Real, Santa Olalla del Cala, Valdelarco, Zufre.<br>
