Extensión, Km<sup>2</sup>: 4938<br>
Altitud, m: (499-900) 714<br>
Pendiente, %: (1-4) 3<br>
Términos municipales: Almonacid de Toledo, Cabañas de Yepes, Cabezamesada, Camuñas, Ciruelos, Consuegra, Corral de Almaguer, Dosbarrios, El Romeral, El Toboso, Huerta de Valdecarabanos, La Guardia, La Puebla de Almoradiel, La Villa de Don Fadrique, Lillo, Madridejos, Manzaneque, Mascaraque, Miguel Esteban, Mora, Noblejas, Ocaña, Ontigola, Quero, Quintanar de la Orden, Santa Cruz de la Zarza, Tembleque, Turleque, Urda, Villacañas, Villafranca de los Caballeros, Villaminaya, Villamuelas, Villanueva de Alcardete, Villanueva de Bogas, Villarrubia de Santiago, Villasequilla, Villatobas, Yepes.<br>
