Extensión, Km<sup>2</sup>: 1917<br>
Altitud, m: (397-858) 542<br>
Pendiente, %: (1-7) 3<br>
Términos municipales: Albarreal de Tajo, Alcabon, Aldea en Cabo, Almorox, Arcicollar, Barcience, Burujon, Camarena, Camarenilla, Carmena, Carriches, Domingo Perez, El Carpio de Tajo, El Casar de Escalona, Erustes, Escalona, Escalonilla, Fuensalida, Garciotun, Gerindote, Hormigos, Huecas, La Mata, La Puebla de Montalban, La Torre de Esteban Hambran, Maqueda, Mentrida, Mesegar de Tajo, Nombela, Noves, Nuño Gomez, Otero, Paredes de Escalona, Pelahustan, Portillo de Toledo, Quismondo, Rielves, Santa Cruz del Retamar, Santa Olalla, Santo-Domingo-Caudilla, Torrijos, Villamiel de Toledo.<br>
