Extensión, Km<sup>2</sup>: 1896<br>
Altitud, m: (399-1271) 703<br>
Pendiente, %: (1-8) 4<br>
Términos municipales: Alcaudete de la Jara, Aldea Nueva de San Bartolome, Aldeanueva de Barbarroya, Belvis de la Jara, El Campillo de la Jara, Espinoso del Rey, La Estrella, La Nava de Ricomalillo, Los Navalmorales, Los Navalucillos, Mohedas de la Jara, Puerto de San Vicente, Retamosa, Robledo del Marzo, San Martin de Pusa, Santa Ana de Pusa, Sevilleja de la Jara, Torrecilla de la Jara, Villarejo de Montalban.<br>
