Extensión, Km<sup>2</sup>: 1893<br>
Altitud, m: (479-796) 595<br>
Pendiente, %: (1-3) 2<br>
Términos municipales: Alameda de la Sagra, Arges, Añover de Tajo, Bargas, Borox, Burguillos de Toledo, Cabañas de la Sagra, Carranque, Casarrubios del Monte, Casasbuenas, Cedillo del Condado, Chozas de Canales, Cobeja, Cobisa, Cuerva, El Viso de San Juan, Esquivias, Galvez, Guadamur, Illescas, Las Ventas de Retamosa, Layos, Lominchar, Magan, Mocejon, Nambroca, Noez, Numancia de la Sagra, Olias del Rey, Palomeque, Pantoja, Polan, Pulgar, Recas, Seseña, Toledo, Totanes, Ugena, Valmojado, Villaluenga de la Sagra, Villaseca de la Sagra, Yeles, Yuncler, Yunclillos, Yuncos.<br>
