Extensión, Km<sup>2</sup>: 1290<br>
Altitud, m: (400-1234) 726<br>
Pendiente, %: (1-11) 5<br>
Términos municipales: Avinyonet del Penedes, Canyelles, Castellet i la Gornal, Castellvi de la Marca, Cubelles, El Pla del Penedes, Font-rubi, Gelida, La Granada, Les Cabanyes, Mediona, Olerdola, Olesa de Bonesvalls, Olivella, Pacs del Penedes, Pontons, Puigdalber, Sant Cugat Sesgarrigues, Sant Llorenþ d'Hortons, Sant Marti Sarroca, Sant Pere de Ribes, Sant Pere de Riudebitlles, Sant Quinti de Mediona, Sant Sadurni d'Anoia, Santa Fe del Penedes, Santa Margarita i els Monjos, Sitges, Subirats, Torrelavit, Torrelles de Foix, Vilafranca del Penedes, Vilanova i la Geltru, Vilubi del Penedes.<br>
