Extensión, Km<sup>2</sup>: 884<br>
Altitud, m: (216-788) 485<br>
Pendiente, %: (1-6) 4<br>
Términos municipales: Aguilar de Segarra, Argenþola, Bellprat, Cabrera d'Igualada, Calaf, Calonge de Segarra, Capellades, Carme, Castellfollit de Ruibregos, Castelloli, Collbato, Corpons, Els Hostalets de Pierola, Els Prats de Rei, Igualada, Jorba, La Llacuna, La Pobla de Claramunt, La Torre de Claramunt, Masquefa, Montmaneu, Odena, Orpi, Piera, Pujalt, Rubio, Sant Marti Sesgueioles, Sant Marti de Tours, Sant Pere Sallavinera, Santa Margarita de Montbui, Santa Maria de Miralles, Vallbona d'Anoia, Veciana, Vilanoba del Cami.<br>
