Extensión, Km<sup>2</sup>: 1081<br>
Altitud, m: (497-2327) 1078<br>
Pendiente, %: (2-21) 10<br>
Términos municipales: Avia, Baga, Berga, Borreda, Capolat, Casserres, Castell de l'Areny, Castellar de n'Hug, Castellar del Riu, Cercs, Figols, Gironella, Gisclareny, Guardiola de Bergueda, L' Espunyola, La Nou de Bergueda, La Pobla de Lillet, La Quar, Montclar, Montmajor, Olvan, Puig-reig, Sagas, Saldes, Sant Jaume de Frontanya, Sant Julia de Cerdanyola, Vallcebre, Vilada, Viver i Serratreix.<br>
