Extensión, Km<sup>2</sup>: 799<br>
Altitud, m: (0-698) 304<br>
Pendiente, %: (1-6) 4<br>
Términos municipales: Badia del Valles, Barbera del Valles, Caldes de Montbui, Castellar del Valles, Cerdanyola del Valles, Gallifa, Matadepera, Montcada i Reixac, Montcada i Reixac, Montcada i Reixac, Palau de Plegamans, Polinya, Ripollet, Rubi, Sabadell, Sant Cugat del Valles, Sant Llorenþ Savall, Sant Quirze del Valles, Santa Perpetua de Mogoda, Sentmenat, Terrassa, Ullastrell, Vacarisses, Viladecavalls.<br>
