Extensión, Km<sup>2</sup>: 431<br>
Altitud, m: (0-305) 164<br>
Pendiente, %: (2-7) 4<br>
Términos municipales: Alella, Arenys de Mar, Arenys de Munt, Argentona, Badalona, Cabrera del mar, Cabrils, Calders, Caldes d'Estrac, Calella, Canet de Mar, Castellcir, Castellterþol, Collsuspina, Dosrius, El Masnou, Granera, L' Estany, Malgrat de Mar, Mataro, Moia, Monistrol de Calders, Montgat, Orrius, Palafolls, Pineda de Mar, Premia de Dalt, Premia del Mar, Sant Adria de Besos, Sant Andreu de Llavaneres, Sant Cebria de Vallalta, Sant Iscle de Vallalta, Sant Pol de Mar, Sant Quirze Safaja, Sant Vicenþ de Montalt, Santa Coloma de Gramenet, Santa Maria d'Olo, Santa Susanna, Teia, Tiana, Tordera, Vilassar de Dalt, Vilassar de Mar.<br>
