Extensión, Km<sup>2</sup>: 1096<br>
Altitud, m: (256-700) 465<br>
Pendiente, %: (1-10) 5<br>
Términos municipales: Artes, Avinyo, Balsareny, Callus, Cardona, Castellbell i el Vilar, Castellfollit del boix, Castellgali, Castellnou de Bages, El Bruc, El Pont de Vilomara i Rocafort, Fonollosa, Gaia, Manresa, Marganell, Monistrol de Montserrat, Mura, Navarcles, Navas, Rajadell, Rellinars, Sallent, San Fruitos de Bages, Sant Joan de Vilatorrada, Sant Mateu de Bages, Sant Salvador de Guardiola, Sant Vicenþ de Castellet, Santpedor, Suria, Talamanca.<br>
