Extensión, Km<sup>2</sup>: 594<br>
Altitud, m: (0-326) 131<br>
Pendiente, %: (1-6) 3<br>
Términos municipales: Abrera, Barcelona, Begues, Caastelldefels, Castellbisbal, Castellvi de Rosanes, Cervello, Corbera  de Llobregat, Cornella de Llobregat, El Papiol, El Prat de Llobregat, Esparraguera, Esplugues de Llobregat, Gava, Hospitalet de Llobregat, Martorell, Molins de Rei, Olesa de Montserrat, Palleja, Sant Andreu de la Barca, Sant Boi de Llobregat, Sant Climent de Llobregat, Sant Feliu de Llobregat, Sant Joan Despi, Sant Just, Sant Just Desvem, Sant Vicenþ dels Horts, Santa Coloma de Cervella, Torrelles de Llobregat, Vallirana, Viladecans.<br>
