Extensión, Km<sup>2</sup>: 573<br>
Altitud, m: (100-526) 288<br>
Pendiente, %: (1-5) 3<br>
Términos municipales: Bigues i Riells, Campins, Canovelles, Canoves i Samalus, Cardedeu, Fogars de Montclus, Fogars de Tordera, Granollers, Gualba, L'Ametlla del Valles, La Garriga, La Llagosta, La Roca del Valles, Les Franqueses del Valles, Llinars del Valles, Lliþa d'Amunt, Lliþa de Vall, Martorelles, Mollet del Valles, Montcada i Reixac, Montmelo, Montornes del Valles, Montseny, Parets del Valles, Sant Antoni de Vilamajor, Sant Celoni, Sant Esteve de Palautordera, Sant Feliu de Codines, Sant Fost de Campsentlles, Sant Pere de Vilamajor, Santa Eulalia de Ronþana, Santa Maria de Martorelles, Santa Maria de Palautordera, Vallgorguina, Vallromanes, Vilanova del Valles, Villalba Sasserra.<br>
