Paleógeno: Arcillas, areniscas, maciños, margas arenosas, conglomerados, limolitas, arcillas rojas, con niveles de areniscas y conglomerados grises, margas azules y areniscas rojas<br>
Cuaternario: Aluvial, terrazas fluviales, arcillas con cantos y conglomerados<br>
Rocas plutónicas: Granitos y leucogranitos biotíticos y granodiorita biotítica de grano medio<br>
Ordovícico: Esquistos cuarzofeldespáticos, porfiroides, grawacas, pizarras azules y pizarras arcillosas negras con graptolites<br>
<br>
<br>
