Neógeno: Arcosas del S. de Caldas de Montbuí, conglomerados pocos cementados, areniscas, arcillas y arcillas amarillas con lentejones de arenisca<br>
Rocas Plutónicas: Granodiorita biotítica de grano medio, con hornblenda accesoria, granitos y leucogranitos biotíticos y granodiorita biotítica<br>
Ordovícico: Micaesquistos, paragneises, esquistos y cuarcitas<br>
Cuaternario: Aluvial, terrazas fluviales, arcillas con cantos, conglomerados y limos con caliche asociados a terraza<br>
<br>
