Rocas plutónicas: Granodiorita biotítica de grano medio con hornblenda accesoria, tonalitas biotíticas-hornbléndicas y granitos y leucogranitos biotíticos<br>
Cuaternario: Aluvial, terrazas fluviales, arcillas con cantos, conglomerados, depósitos de arroyada y coluviones antiguos<br>
Carbonífero: Alternancia de conglomerados, areniscas, cuarcitas y pizarras<br>
Ordovícico: Micaesquistos, paragneises, esquistos y cuarcitas<br>
<br>
