Extensión, Km<sup>2</sup>: 863<br>
Altitud, m: (0-1476) 527<br>
Pendiente, %: (3-18) 9<br>
Términos municipales: Alcaucin, Algarrobo, Almachar, Archez, Arenas, Benamargosa, Benamocarra, Canillas de Aceituno, Canillas de Albaida, Comares, Competa, Cutar, El Borge, Frigiliana, Iznate, Macharaviaya, Moclinejo, Nerja, Periana, Rincon de la Victoria, Salares, Sayalonga, Sedella, Torrox, Totalan, Velez Malaga, Viñuela.<br>
