Extensión, Km<sup>2</sup>: 2482<br>
Altitud, m: (365-1464) 589<br>
Pendiente, %: (1-12) 6<br>
Términos municipales: Alameda, Alfarnate, Alfarnatejo, Almargen, Antequera, Archidona, Ardales, Campillo, Casabermeja, Cañete la Real, Colmenar, Cuevas Bajas, Cuevas de San Marcos, Cuevas del Becerro, Fuente de Piedra, Humilladero, Molina, Riogordo, Sierra de Yeguas, Teba, Villanueva de Algaidas, Villanueva de Tapia, Villanueva del  Rosario, Villanueva del Trabuco.<br>
