Extensión, Km<sup>2</sup>: 2585<br>
Altitud, m: (0-1636) 406<br>
Pendiente, %: (1-15) 8<br>
Términos municipales: Alhaurin de la Torre, Alhaurin el Grande, Almogia, Alora, Alozaina, Benahavis, Benalmadena, Carratraca, Cartama, Casarabonela, Casares, Coin, Estepona, Fuengirola, Guaro, Istan, Malaga, Manilva, Marbella, Mijas, Monda, Ojen, Pizarra, Tolox, Torremolinos, Valle de Abdalajis, Yunquera.<br>
