Precámbrico: Pizarras, esquistos biotíticos, areniscas y gneises anfibolíticos<br>
Cámbrico: Cuarcitas blancas, microconglomerados, pizarras negras con intercalaciones arenosas y cuarcíticas, calizas y dolomías<br>
Rocas graníticas hercínicas: Granodioritas y granitos biotíticos precoces<br>
Cuaternario: Depósitos aluviales, fondos de vaguada y terrazas<br>
Terciario: Arcillas, arenas y gravas <br>
<br>
