Cámbrico: Pizarras negras, cuarcitas, areniscas, cuarcitas de Gistral, microconglomerados, cuarcitas de Cándana superior, pizarras y esquistos<br>
Rocas igneas: Granitoides de tendencia calcoalcalina poco o nada deformados y granitoides con tendencia alcalina poco o nada deformados<br>
Cuaternario: Indiferenciado, depósitos de ladera y fluviotorrenciales sobre la rasa, depósitos de cantos marinos y suelos sobre la rasa<br>
<br>
