Rocas graníticas hercínicas: Granitos y granodioritas predominantemente biotíticos, facies con megacristales y granitos de dos micas moderadamente leucocráticos<br>
Silúrico: Esquistos, esquistos grafitosos, filitas, ampelitas, liditas, pizarras con cloritoides y ampelitas<br>
Ordovícico: Cuarcita armoricana, pizarras grises y negras<br>
Cuaternario: Terrazas, cantos, arenas, abanicos aluviales, arcillas, glacis degradados y gravas<br>
<br>
