Extensión, Km<sup>2</sup>: 1629<br>
Altitud, m: (440-1100) 719<br>
Pendiente, %: (1-6) 4<br>
Términos municipales: Abengibre, Alatoz, Alborea, Alcala del Jucar, Balsa de Ves, Carcelen, Casas de Ves, Casas-Ibañez, Cenizate, Fuentealbilla, Golosalvo, Jorquera, Jorquera, La Recueja, Madrigueras, Mahora, Motilleja, Navas de Jorquera, Pozo-Lorente, Valdeganga, Villa de Ves, Villamalea, Villatoya, Villavalient.<br>
