Extensión, Km<sup>2</sup>: 1937<br>
Altitud, m: (786-1666) 1089<br>
Pendiente, %: (1-7) 4<br>
Términos municipales: Alcaraz, Balazote, Bienservida, Casas de Lazaro, Cotillas, Dehesa de Santiago (Cotillas y Villaverde de Guadalimar), Dehesa de Santiago (Cotillas y Villaverde de Guadalimar), El Ballestero, Masegoso, Mesillas, Paterna del Madera, Peñascosa, Povedilla, Riopar, Robledo, Salobre, San Pedro, Vianos, Villapalacios, Villaverde de Guadalimar, Viveros.<br>
