Neógeno: Arcillas arenosas, calizas arcillosas, arcillas, margas, indiferenciado, conglomerados, brechas, margas arenosas, arcillas molásicas y calizas<br>
Cretácico: Areniscas, calizas arenosas, indiferenciado, calizas, margas, Facies Utrillas, arenas y arcillas<br>
Cuaternario: Indiferenciado, arenas, arcillas y cantos<br>
Triásico: Arcillas, yesos y arcillas abigarradas <br>
<br>
<br>
<br>
<br>
