Cretácico: Indiferenciado, calizas oolíticas, calcarenitas, calizas, margocalizas y margas<br>
Neógeno: Calizas, margas, arenas, arcillas, areniscas, calizas recifales mas o menos arenosas, margas arenosas y conglomerados<br>
Jurásico: Dolomías, indiferenciado, calizas oolíticas, micritas, arcillas, margocalizas y calizas nodulosas<br>
Cuaternario: Rañas, coluviones, indiferenciado y travertinos<br>
Triásico: Areniscas, arcillas, margas y lignitos<br>
<br>
