Extensión, Km<sup>2</sup>: 1368<br>
Altitud, m: (500-868) 667<br>
Pendiente, %: (1-7) 3<br>
Términos municipales: Aldea de Fresno, Arroyomolinos, Batres, Cadalso de los Vidrios, Casarrubuelas, Cenicientos, Chapineria, Colmenar del Arroyo, Colmenarejo, Cubas de la Sagra, El Alamo, Fuenlabrada, Griñon, Humanes de Madrid, Moraleja de Enmedio, Mostoles, Navalagamella, Navalcarnero, Navas del Rey, Parla, Pelayos de la Presa, Rozas de Puerto Real, San Martin de Valdeiglesias, Serranillos del Valle, Sevilla la Nueva, Torrejon de Velasco, Torrejon de la Calzada, Valdemorillo, Valdemoro, Villa del Prado, Villamanta, Villamantilla, Villanueva de Perales.<br>
