Extensión, Km<sup>2</sup>: 1307<br>
Altitud, m: (499-800) 642<br>
Pendiente, %: (1-4) 2<br>
Términos municipales: Ambite, Aranjuez, Belmonte de Tajo, Brea de Tajo, Carabaña, Chinchon, Cienpozuelos, Colmenar de Oreja, Estremera, Fuentidueña de Tajo, Morta de Tajuña, Orusco de Tajuña, Perales de Tajuña, San Martin de la Vega, Tielmes, Titulcia, Valdaracete, Valdelaguna, Villaconejos, Villamanrique de Tajo, Villarejo de Salvanes.<br>
