Extensión, Km<sup>2</sup>: 1079<br>
Altitud, m: (600-876) 723<br>
Pendiente, %: (1-5) 3<br>
Términos municipales: Ajalvir, Alcala de Henares, Algete, Anchuelo, Arganda del Rey, Camarma de Esteruelas, Campo Real, Cobeña, Corpa, Daganzo de Arriba, Fresno de Torete, Fuente el Saz de Jarama, Loeches, Los Santos de la Humosa, Meco, Nuevo Baztan, Olmeda de las Fuentes, Pezuela de la Torres, Pozuelo del Rey, Ribatejada, Santorcaz, Talamanca de Jarama, Torres de la Alameda, Valdeavero, Valdeolmos-Alalpardo, Valdepielagos, Valdetorres de Jarama, Valdilecha, Valverde de Alcala, Villalbilla, Villar de Olmo.<br>
