Extensión, Km<sup>2</sup>: 1763<br>
Altitud, m: (550-964) 677<br>
Pendiente, %: (1-3) 2<br>
Términos municipales: Alcobendas, Alcorcon, Boadilla del Monte, Brunete, Colmenar Viejo, Coslada, Getafe, Las Rozas se Madrid, Leganes, Madrid, Majadahonda, Mejorada del Campo, Paracuellos de Jarama, Pinto, Pozuelo de Alarcon, Quijoma, Rivas-Vaciamadrid, San Fernando de Henares, San Sebastian de los Reyes, Torrejon de Ardoz, Tres Cantos, Vellida de San Antonio, Villanueva de la Cañada, Villanueva del Pardillo, Villaviciosa de Odon.<br>
