Extensión, Km<sup>2</sup>: 972<br>
Altitud, m: (801-1579) 1108<br>
Pendiente, %: (1-16) 7<br>
Términos municipales: Alpedrete, Becerril de la Sierra, Cercedilla, Cercedilla y Navacerrada, Collado Mediano, Collado Villalba, El Boalo, El Boalo y Manzanares, El Escorial, Fresnadillas de la Oliva, Galapagar, Guadarrama, Hoyo de Manzanares, Los Molinos, Manzanares el Real, Moralzarzal, Navacerrada, Robledo de Chavela, San Lorenzo de El Escorial, Santa Maria de la Alameda, Torrelodones, Valdemaqueda, Zarzalejo.<br>
