Extensión, Km<sup>2</sup>: 2462<br>
Altitud, m: (537-2993) 1252<br>
Pendiente, %: (1-21) 10<br>
Términos municipales: Aren, Benabarre, Benasque, Bisaurri, Bonansa, Campo, Capella, Castellon de Sos, Castigaleu, Chia, Estopiñan del Castillo, Foradada del Toscar, Graus, Isabena, La Puebla de Castro, Lascuarre, Laspaules, Monesma y Cajigar, Montanuy, Perarrua, Puente de Montañana, Sahun, Santaliestra y San Quilez, Seacastilla, Seira, Sesue, Sopeira, Tolva, Torre la Ribera, Valle de Bardaji, Valle de Lierp, Veracruz, Viacamp y Litera, Villanova.<br>
