Extensión, Km<sup>2</sup>: 1177<br>
Altitud, m: (301-1050) 551<br>
Pendiente, %: (1-12) 6<br>
Términos municipales: Abiego, Adahuesca, Alquezar, Azara, Azlor, Barbastro, Barbuñales, Barcabo, Berbegal, Bierge, Castejon del Puente, Castillazuelo, Colungo, El Grado, Estada, Estadilla, Fonz, Hoz y Costean, Ilche, Laluenga, Laperdiguera, Lascellas-Ponzano, Naval, Olvena, Peraltilla, Pozan de Vero, Salas Altas, Salas Bajas, Santa Maria de Dulcis.<br>
