Extensión, Km<sup>2</sup>: 3007<br>
Altitud, m: (600-2512) 1237<br>
Pendiente, %: (1-19) 9<br>
Términos municipales: Aisa, Anso, Arag³es del Puerto, Bailo, Biescas, Borau, Caldearenas, Canal de Berdun, Canfranc, Castiello de Jaca, Comunero de Anso y Fago, Fago, Hoz de Jaca, Jaca, Jasa, Panticosa, Puente la Reina de Jaca, Sabiñanigo, Sallent de Gallego, Santa Cilia de Jaca, Santa Cruz de la Seros, Valle de Hecho, Villanua, Yebra de Basa, Yesero.<br>
