Extensión, Km<sup>2</sup>: 3012<br>
Altitud, m: (329-1607) 605<br>
Pendiente, %: (1-10) 5<br>
Términos municipales: Ag³ero, Albero Alto, Albero Bajo, Alcala de Gurrea, Alcala de Obispo, Alerre, Almudaver, Almuniente, Ang³es, Antillon, Argavieso, Arguis, Ayerbe, Banastas, Barbues, Biscarrues, Blecua y Torres, Casbas de Huesca, Chimillas, Grañen, Gurrea de Gallego, Huerto, Huesca, Ibieca, Igries, La Sotonera, Las Peñas de Riglos, Loarre, Loporzano, Loscorrales, Lupiñen-Ortilla, Monflorite-Lascasas, Novales, Nueno, Pertusa, Piraces, Quicena, Robres, Salillas, Sangarren, Senes de Alcubierre, Sesa, Sietamo, Tardienta, Tierz, Torralba de Aragon, Torres de Alcanadre, Torres de Barbues, Tramaced, Vicien.<br>
