Paleógeno: Margas, calizas, calizas detríticas, conglomerados, areniscas y arcillas<br>
Cretácico: Calizas, areniscas, margas y calizas margosas<br>
Carbonífero: Pizarras micáceas, microconglomerados, areniscas, calizas y granodioritas<br>
Devónico: Pizarras, calizas arcillosas, grawacas, cuarcitas, dolomitas, calizas, mármoles, calcosilicatos, esquistos, silimanita y migmatitas<br>
Triásico: Areniscas, arcillas, conglomerados, yesos y margas<br>
Rocas plutónicas: Biotita granodiorita<br>
<br>
<br>
<br>
