Paleógeno: Nivel calizo, facies de transición marino-continental, arcillas, margas, areniscas, calizas, yesos, conglomerados, conglomerados masivos y brechas<br>
Devónico: Pizarras, calizas arcillosas, grawacas, calizas, cuarcitas y dolomitas<br>
Cuaternario: Morrenas, conglomerados y brechas<br>
Cretácico: Calizas, areniscas y margas<br>
Carbonífero: Grawacas, pizarras y calizas<br>
Rocas ácidas: Granitos<br>
<br>
