Neógeno: Margas, areniscas, calizas arenosas, margas arenosas, maciños, conglomerados, arenas y limos <br>
Cuaternario: Indiferenciado, aluvial, calizas molásicas, conglomerados, arenas y arcillas <br>
Triásico: Margas, arcillas, yesos e indiferenciado <br>
Cretácico: Calizas, dolomías, dolomías arenosas, margocalizas, margas y calizas <br>
Rocas volcánicas: Subvolcánicas básicas y volcánicas	<br>
<br>
<br>
