Extensión, Km<sup>2</sup>: 677<br>
Altitud, m: (200-901) 523<br>
Pendiente, %: (1-7) 4<br>
Términos municipales: Arboli, Asco, Bellmunt del Priorat, Benissanet, Cabaces, Capafonts, Capþanes, Cornudella de Montsant, El Lloar, El Masroig, El Molar, Els Guiamets, Falset, Flix, Garcia, Ginestar, Gratallops, La Bisbal de Falset, La Febro, La Figuera, La Morera de Montsant, La Palma d'Ebre, La Torre de Fontaubella, La Vilella Alta, La Vilella Baixa, Margale, Marþa, Miravet, Mont-ral, Mora d'Ebre, Mora la Nova, Poboleda, Porrera, Pradell de la Teixeta, Prades, Rasquera, Riba-roja d'Ebre, Tivissa, Torroja del Priorat, Ulldemolins, Vilanova de Prades, Vinebre, la Torre de l'Espanyol.<br>
