Extensión, Km<sup>2</sup>: 1741<br>
Altitud, m: (0-1030) 256<br>
Pendiente, %: (1-12) 5<br>
Términos municipales: Alcanar, Aldover, Alfara de Carles, Amposta, Benifallet, Camartes, Deltebre, El Perello, Freginals, Godall, L'Aldea, L'Ametlla de Mar, L'Ampolla, La Galera, La Senia, Mas de Barberans, Masdenverge, Paüls, Roquetes, Sant Carles de la Rapita, Sant Jaume d'Enveja, Santa Barbara, Tivenys, Tortosa, Ulldecona, Xerta.<br>
