Cuaternario: Gravas, conglomerados, arcillas, terrazas bajas, conos de deyección, llanura deltáica, aluvial, coluvión orla y abanicos aluviales<br>
Jurásico: Calizas, dolomías, margas y areniscas<br>
Cretácico: Calizas, conglomerados, areniscas, arcillas, calizas bioclásticas y arenosas, calizas con Tourcasias y Orbitolinas y margas<br>
Triásico: Calizas, dolomías, argiolitas, yesos, margas y arcillas abigarradas<br>
<br>
