Cuaternario: Abanicos aluviales encostrados, mantos de arroyada, terrazas bajas, limos y aluvial-coluvial<br>
Carbonífero: Pizarras y areniscas con liditas y calizas en la base<br>
Neógeno: Argiolitas, areniscas, conglomerados, calcisilitas, lumaquelas y arcillas<br>
Triásico: Calizas, dolomías, lutitas rojas, yesos, conglomerados y areniscas<br>
Cretácico: Dolomías negras masivas, calizas tableadas, brechas dolomíticas, dolomías y calizas<br>
<br>
