Extensión, Km<sup>2</sup>: 1534<br>
Altitud, m: (778-908) 831<br>
Pendiente, %: (1-4) 3<br>
Términos municipales: Alba de Cerrato, Antigüedad, Baltanas, Castrillo de Don Juan, Castrillo de Onielo, Cevico Navero, Cevico de la Torre, Cobos de Cerrato, Cordovilla la Real, Cubillas de Cerrato, Dueñas, Espinosa de Cerrato, Hermedes de Cerrato, Herrera de Valdecañas, Hontoria de Cerrato, Hornillos de Cerrato, Magaz de Pisuerga, Palenzuela, Poblacion de Cerrato, Quintana del Puente, Reinoso de Cerrato, Soto de Cerrato, Tabanera de Cerrato, Tariego de Cerrato, Torquemada, Valbuena de Pisuerga, Valdeolmillos, Valle de Cerrato, Venta de Baños, Vertavillo, Villaconancio, Villahan, Villamediana, Villamuriel de Cerrato, Villaviudas, Villodrigo.<br>
