Extensión, Km<sup>2</sup>: 637<br>
Altitud, m: (879-1100) 959<br>
Pendiente, %: (1-3) 2<br>
Términos municipales: Alar del Rey, Bascones de Ojeda, Calahorra de Boedo, Collazos de Ojeda, Dehesa de Romanos, Herrera de Pisuerga, La Vid de Ojeda, Micieces de Ojeda, Olea de Boedo, Olmos de Ojeda, Paramo de Boedo, Payo de Ojeda, Pradanos de Ojeda, Revilla e los Collazos, San Cristobal de Boedo, Santa Cruz de Boedo, Santibañez de Ecla, Sotobañado y Priorato, Villameriel, Villaprovedo.<br>
