Extensión, Km<sup>2</sup>: 1018<br>
Altitud, m: (888-1100) 982<br>
Pendiente, %: (1-3) 2<br>
Términos municipales: Ayuela, Buenavista de Valdavia, Bustillo de la Vega, Congosto de Valdavia, La Puebla de Valdavia, La Serna, Lagartos, Ledigos, Pedrosa de la Vega, Pino del Rio, Poza de la Vega, Quintanilla de Onsoña, Renedo de la Vega, Saldaña, Santervas de la Vega, Tabanera de Valdavia, Valderrabano, Villabasta de Valdavia, Villaeles de Valdavia, Villaluenga de la Vega, Villameriel, Villamoronta, Villanuño de Valdavia, Villarabe, Villasila de Valdavia, Villota del Paramo.<br>
