Extensión, Km<sup>2</sup>: 2337<br>
Altitud, m: (200-1355) 775<br>
Pendiente, %: (1-13) 7<br>
Términos municipales: Alfoz de Bricia, Alfoz de Santa Gadea, Arija, Berberana, Espinosa de los Monteros, Junta de Trasloma, Junta de Villalba de Losa, Jurisdiccion de San Zadomil, Medina de Pomar, Merindad de Cuesta-Urria, Merindad de Montija, Merindad de Sotoscueva, Merindad de Valdeporres, Merindad de Valdivieso, Trespademe, Valle de Losa, Valle de Manzanedo, Valle de Mena, Valle de Tobalina, Valle de Valdebezana, Valle de Zamanzas, Villarcayo de Merindad de Castilla la Vieja.<br>
