Extensión, Km<sup>2</sup>: 2044<br>
Altitud, m: (337-1447) 640<br>
Pendiente, %: (1-11) 5<br>
Términos municipales: Aguaron, Aguilon, Alfamen, Almonacid de la Sierra, Alpartir, Arandiga, Calatorao, Calcena, Cariñena, Chodes, Codos, Cosuenda, Encinacorba, Epila, La Almunia de Doña Godina, Longares, Lucena de Jalon, Lumpiaque, Mesones de Isuela, Mezalocha, Morata de Jalon, Muel, Nigüella, Paniza, Plasencia de Jalon, Purujosa, Ricla, Rueda de Jalon, Salillas de Jalon, Santa Cruz de Grio, Tabuenca, Tierga, Tobed, Tosos, Trasobares, Urrea de Jalon, Villanueva de Huerva.<br>
