Extensión, Km<sup>2</sup>: 1098<br>
Altitud, m: (251-1093) 561<br>
Pendiente, %: (1-12) 5<br>
Términos municipales: Agon, Ainzon, Alberite de San Juan, Albeta, Alcala de Moncayo, Ambel, Añon de Moncayo, Bisimbre, Borja, Bulbuente, Bureta, El Buste, Frescano, Fuendejalon, Gallur, Grisel, Litago, Lituenigo, Los Fayos, Magallon, Malejan, Mallen, Malon, Novallas, Novillas, Pozuelo de Aragon, San Martin de la Virgen de Moncayo, Santa Cruz de Moncayo, Talamantes, Tarazona, Torrellas, Trasmoz, Vera de Moncayo, Vierlas.<br>
