Extensión, Km<sup>2</sup>: 1247<br>
Altitud, m: (778-1210) 962<br>
Pendiente, %: (1-6) 3<br>
Términos municipales: Abanto, Acered, Aladren, Aldehuela de Liestos, Anento, Atea, Badules, Balconchan, Berrueco, Cerveruela, Cubel, Daroca, Fombuena, Gallocanta, Herrera de los Navarros, Langa del Castillo, Las Cuerlas, Lechon, Luesma, Mainar, Manchones, Murero, Nombrevilla, Orcajo, Retascon, Romanos, Santed, Torralba de los Frailes, Torralbilla, Used, Val de San Martin, Valdehorna, Villadoz, Villafeliche, Villanueva de Jiloca, Villar de los Navarros, Villareal de Huerva, Villaroya del Campo, Vistabella.<br>
