Extensión, Km<sup>2</sup>: 3383<br>
Altitud, m: (270-1300) 564<br>
Pendiente, %: (1-9) 4<br>
Términos municipales: Ardisa, Artieda, Asin, Bagües, Biel-Fuencalderas, Biota, Castejon de Valdejasa, Castiliscar, Ejea de los Caballeros, El Frago, Erla, Isuerre, Las Pedrosas, Layana, Lobera de Onsella, Longas, Los Pintanos, Luesia, Luna, Mianos, Murillo de Gallego, Navardun, Ores, Piedratajada, Pradilla de Ebro, Puendeluna, Sadaba, Salvatierra de Esca, Santa Eulalia de Gallego, Sierra de Luna, Sigües, Sos del Rey Catolico, Tauste, Uncastillo, Undues de Lerda, Urries, Valpalmas.<br>
