Neógeno: Margas, areniscas, conglomerados, arcillas, arenas, calizas, yesos y limos yesíferos<br>
Cámbrico: Cuarcitas, pizarras, areniscas, grawacas, dolomías, calizas y rocas volcánicas<br>
Triásico: Areniscas, conglomerados, arcillas abigarradas, yesos, calizas y calizas dolomíticas<br>
Cretácico: Indiferenciado, margas y calizas<br>
Cuaternario: Brechas, conglomerados, gravas, arcillas e indiferenciado<br>
<br>
