Extensión, Km<sup>2</sup>: 1559<br>
Altitud, m: (699-1377) 1035<br>
Pendiente, %: (1-7) 4<br>
Términos municipales: Alcocer, Alhondiga, Alique, Alocen, Arbeteta, Armallones, Auñon, Berninches, Budia, Castilforte, Chillaron del Rey, Duron, El Olivar, El Recuenco, Escamilla, Mantiel, Millana, Pareja, Peralveche, Peñalen, Poveda de la Sierra, Sacedon, Salmeron, Trillo, Valtablado del Rio, Villanueva de Alcoron, Zaorejas.<br>
