Jurásico: Calizas, areniscas, margas, calizas con silex, dolomías, carniolas, yesos, brechas calcareo-dolomíticas, indiferenciado y calizas dolomíticas<br>
Triásico: Areniscas, conglomerados, margas, yesos, pizarras y cuarcitas<br>
Cretácico: Calizas, dolomías, margas, areniscas, arenas y arcillas<br>
Cuaternario: Indiferenciado, derrubios de laderas, arenas y arcillas<br>
Ordovícico: Pizarras y cuarcitas<br>
<br>
