Extensión, Km<sup>2</sup>: <br>
Altitud, m: <br>
Pendiente, %: <br>
Términos municipales: Agaete, Agüimes, Arterana, Arucas, Firgas, Galdar, Ingenio, Las Palmas de Gran Canaria, Morgan, Moya, San Bartolome de Tirajana, San Nicolas de Tolentino, Santa Brigida, Santa Lucia de Tirajana, Santa Maria de Guia de Gran Canaria, Teide, Tejeda, Teror, Valleseco, Valsequillo de Gran Canaria, Vega de San Mateo.<br>
