Extensión, Km<sup>2</sup>: 2504<br>
Altitud, m: (0-502) 199<br>
Pendiente, %: (1-6) 4<br>
Términos municipales: A Coruña, Abegondo, Ares, Arteixo, Bergondo, Betanzos, Cabana, Cabarras, Cambre, Carballo, Cariño, Carral, Cedeira, Cerdido, Cesuras, Coiros, Coristanco, Culleredo, Fene, Ferrol, Laracha, Malpica de Bergantiños, Mañon, Miño, Moeche, Mugardos, Naron, Neda, Oleiros, Ortigueira, Oza dos Rios, Paderne, Ponteceso, Pontedeume, Sada, San Sadurniño, Valdoviño, Vilarmaior.<br>
