Extensión, Km<sup>2</sup>: 2840<br>
Altitud, m: (0-426) 235<br>
Pendiente, %: (1-10) 5<br>
Términos municipales: A Baña, Ames, Boiro, Boquixon, Brion, Camariñas, Carnota, Cee, Corcubion, Dodro, Dumbria, Fisterra, Laxe, Lousame, Mazaricos, Muros, Muxia, Negreira, Noia, Outes, Padron, Pobra do Caramiñal, Porto do Son, Rianxo, Ribeira, Rois, Santa Comba, Santiago de Compostela, Teo, Vedra, Vimianzo, Zas.<br>
