Precámbrico-Ordovícico: Esquistos, metagrawacas, paragneis y rocas ultramórficas, generalmente serpentinizadas<br>
Ordovícico: Pizarras, arenisca, cuarcitas, cuarcita armoricana, gneises microglandulares, cuarcitas feldespáticas, esquistos y pizarra negra<br>
Rocas graníticas hercínicas: Granitos de dos micas con megacristales, granodioritas y granitos biotíticos precoces<br>
Silúrico: Pizarras y ampelitas<br>
<br>
