Extensión, Km<sup>2</sup>: 1947<br>
Altitud, m: (66-1106) 802<br>
Pendiente, %: (1-5) 3<br>
Términos municipales: Alcañices, Carbajales de Alba, Faramontanos de Tabara, Ferreras de Abajo, Ferreruela, Figueruela de Arriba, Fonfria, Gallegos del Rio, Losacino, Losacio, Mahide, Manzanal del Barco, Moreruela de Tabara, Olmillos de Castro, Perilla de Castro, Pino, Pozuelo de Tabara, Rabanales, Rabano de Aliste, Riofrio de Aliste, Samir de los Caños, San Vicente de la Cabeza, San Vitero, Santa Eufemia del Barco, Tabara, Trabazos, Vegalatrave, Videmala, Villalcampo, Viñas.<br>
