Extensión, Km<sup>2</sup>: 1486<br>
Altitud, m: (599-872) 768<br>
Pendiente, %: (1-6) 3<br>
Términos municipales: Alfaraz de Sayago, Almeida de Sayago, Argañin, Bermillo de Sayago, Cabañas de Sayago, Carbellino, Fariza, Fermoselle, Fresno de Sayago, Gamones, Luelmo, Mayalde, Moral de Sayago, Moraleja de Sayago, Moralina, Muga de Sayago, Pereruela, Peñausende, Roelos de Sayago, Salce, Torregamones, Villadepera, Villar del Buey, Villardiegua de la Ribera.<br>
