Extensión, Km<sup>2</sup>: 1999<br>
Altitud, m: (800-2001) 1191<br>
Pendiente, %: (1-12) 6<br>
Términos municipales: Asturianos, Cernadilla, Cobreros, Espadañedo, Ferreras de Arriba, Galende, Hermisende, Justel, Lubian, Manzanal de Arriba, Manzanal de los Infantes, Molezuelas de la Carballeda, Mombuey, Muela de los Caballeros, Otero de Bodas, Palacios de Sanabria, Pedralba de la Padreria, Peque, Pias, Porto, Puebla de Sanabria, Requejo, Rionegro del Puente, Robleda-Cervantes, Rosinos de la Requejada, San Justo, Trefacio, Villadeciervos.<br>
