Extensión, Km<sup>2</sup>: 1513<br>
Altitud, m: (698-895) 773<br>
Pendiente, %: (1-2) 2<br>
Términos municipales: Arcenillas, Argujillo, Casa Seca de Campean, Casaseca de las Chanas, Castrillo de la Guareña, Cazurra, Cañizal, Corrales, Cuelgamures, El Cubo de Tierra del Vino, El Maderal, El Pego, El Perdigon, El Piñero, Entrala, Fuentelapeña, Fuentesauco, Fuentespreadas, Gema, Guarrate, Jambrina, La Boveda de Toro, Madridanos, Morale de Toro, Moraleja del Vino, Morales de Vino, Peleagonzalo, Peleas de Abajo, San Miguel de la Ribera, Santa Clara de Avedillo, Sanzoles, Toro, Vadillo de la Guareña, Valdefinjas, Vallesa de la Guareña, Venialbo, Villabuena del Puente, Villaescusa, Villalazan, Villamor de los Escuderos, Villanueva de Campean, Villaralbo.<br>
