Extensión, Km<sup>2</sup>: 443<br>
Altitud, m: (0-601) 254<br>
Pendiente, %: (1-6) 4<br>
Términos municipales: Albalat dels Tarongers, Alfara de Algimia, Algar de Palancia, Algimia de Alfara, Benavites, Benifairo de les Valls, Canet d'En Berenguer, Emperador, Estivella, Faura, Gilet, La Pobla de Farnals, Massalfassar, Massamagrell, Museros, Naquera, Petres, Puig, Puþol, Quart de les Valls, Quartell, Rafelbunyol, Sagunt, Segart, Serra, Torres Torres, Valencia.<br>
