Extensión, Km<sup>2</sup>: 723<br>
Altitud, m: (200-903) 459<br>
Pendiente, %: (1-9) 4<br>
Términos municipales: Agullent, Aielo de Malferit, Albaida, Alfarrasi, Atzeneta d'Albaida, Ayelo de Rugat, Belgida, Bellus, Beniatjar, Benicolet, Beniganim, Benisoda, Benisuera, Bocairent, Bufali, Carricola, Castello de Rugat, Fontanars dels Alforins, Guadasequies, I' Olleria, La Pobla del Duc, Llutxent, Montaverner, Montichelvo, Ontinyent, Otos, Palomar, Pinet, Quatretonda, Rafol de Salem, Rugat, Salem, Sempere, Terrateig, Xativa.<br>
