Extensión, Km<sup>2</sup>: 562<br>
Altitud, m: (0-100) 61<br>
Pendiente, %: (1-2) 2<br>
Términos municipales: Alaquas, Albal, Albalat dels Sorells, Alboraya, Albuixech, Alcacer, Aldaia, Alfafar, Alfara del Patriarca, Almassera, Benetusser, Beniparrell, Bonrepos i Mirambell, Burjassot, Catarroja, Foios, Godella, I' Eliana, Lugar Nuevo de la Corona, Manises, Massanassa, Meliana, Mislata, Moncada, Paiporta, Paterna, Picanya, Picassent, Quart de Poblet, Rocafort, San Antonio de Benageber, Sedavi, Silla, Tavernes Blanques, Torrent, Valencia, Valencia, Valencia, Valencia, Valencia, Valencia, Vinalesa, Xirivella.<br>
