Extensión, Km<sup>2</sup>: 941<br>
Altitud, m: (0-469) 118<br>
Pendiente, %: (1-5) 3<br>
Términos municipales: Albalat de la Ribera, Alberic, Alcantera de Xuquer, Algemesi, Alginet, Almussafes, Alzira, Antella, Beneixida, Benifaio, Benimodo, Benimuslem, Carcaixent, Carcer, Carlet, Castello de la Ribera, Corbera, Cotes, Cullera, Favara, Fortaleny, Gavarda, Guadassuar, L'Alcudia, La Pobla Llarga, Llauri, Masalaves, Polinya de Xuquer, Riola, San Juan de Enova, Sellent, Senyera, Sollana, Sueca, Sumacarcer, Tous, Xativa.<br>
