Extensión, Km<sup>2</sup>: 430<br>
Altitud, m: (0-402) 157<br>
Pendiente, %: (2-13) 6<br>
Términos municipales: Ador, Alfauir, Almisera, Almoines, Barx, Bellreguard, Beniarjo, Benifairo de la Valldigna, Benifla, Benirredra, Castellonet de la Conquesta, Daimus, Gandia, Guardamar, L' Alqueria de la Comtessa, La Font d'En Carros, Llocnou de Sant Jeroni, Miramar, Oliva, Palma de Gandia, Palmera, Piles, Potries, Rafelcofer, Real de Gandia, Rotova, Simat de la Valldigna, Tavernes de la Valldigna, Villalonga, Xeraco, Xeresa.<br>
