Cuaternario: Conglomerados, arcillas con cantos, mantos de arrollada, piedemonte, limos pardos y negros, albuferas, marismas, arenas, gravas, limos, aluviales, terrazas e indiferenciado<br>
Triásico: Dolomías, margas, calizas, areniscas y limolitas rojas<br>
Jurásico: Brechas, dolomías, calizas, margas y calizas margosas<br>
Neógeno: Lutitas rojas, areniscas, conglomerados y lutitas con niveles lumaquélicos de Ostreidos<br>
<br>
