Jurásico: Margas, calizas margosas, calizas ,calizas pisolítitcas, areniscas y calizas<br>
Cretácico: Margas, arcillas, areniscas, calizas, arcillas verdes en la base, calcarenitas con ostreidos, calizas dolomíticas y brechas<br>
Triásico: Arcillas abigarradas, yesos, dolomías, calizas, margas, conglomerados, areniscas y limolitas<br>
Cuaternario: Glacis, mantos de arrollada, aluviones y terrazas<br>
<br>
