Cuaternario: Glacis, mantos de arrollada, costras calcáreas, travertinos, aluviones, terrazas y coluviones<br>
Jurásico: Margas, calizas margosas, calizas, calizas oolíticas, calizas con silex, calizas pisolíticas y areniscas<br>
Neógeno: Calizas algales, lutitas rojas, margas, conglomerados y areniscas<br>
Cretácico: Calcarenitas con ostreidos, arenas, margas, calizas, areniscas y arcillas<br>
<br>
