Neógeno: Lutitas rojas, margas, calizas, conglomerados, areniscas, lutitas, lumaquelas con ostreidos y calizas algales<br>
Cretácico: Calizas, margas, dolomías, arenas blancas y amarillentas, arcillas y calcarenitas con ostreidos<br>
Jurásico: Brechas, dolomías, calizas, calizas oolíticas y calizas con silex<br>
Cuaternario: Aluviones, terrazas, glacis y mantos de arrollada<br>
Triásico: Arcillas abigarradas y yesos<br>
<br>
