Extensión, Km<sup>2</sup>: 1428<br>
Altitud, m: (789-1001) 871<br>
Pendiente, %: (1-4) 3<br>
Términos municipales: Abusejo, Aldehuela de Yeltes, Aldehuela de la Boveda, Barbalos, Berrocal de Huebra, Boada, Buenamadre, Cabrillas, Carrascal del Obispo, Castraz, Garcirrey, La Fuente de San Esteban, La Sagrada, Las Veguillas, Martin de Yeltes, Matilla de los Caños del Rio, Membribe de la Sierra, Morille, Narros de Matalayegua, Pelarrodriguez, Puebla de Yeltes, Retortillo, Robliza de Cojos, San Muñoz, San Pedro de Rozados, Sanchon de la Sagrada, Seprulco-Hilario, Tamames, Vecinos, Villalba de los Llanos.<br>
