Extensión, Km<sup>2</sup>: 910<br>
Altitud, m: (800-911) 866<br>
Pendiente, %: (1-2) 2<br>
Términos municipales: Alaraz, Alconada, Aldeaseca de la Frontera, Boveda del Rio Almar, Cantalapiedra, Cantalpino, Cantaracillo, El Campo de Peñaranda, Macotera, Malpartida, Mancera de Abajo, Nava de Sotrobal, Palaciosrubios, Parandinas de San Juan, Peñaranda de Bracamonte, Proveda de las Cintas, Ragama, Salmoral, Santiago de la Puebla, Tarazona de Guareña, Tordillos, Ventosa del Rio Almar, Villaflores, Villar de Gallimazo, Villoria, Zorita de la Frontera.<br>
