Extensión, Km<sup>2</sup>: 1080<br>
Altitud, m: (749-900) 809<br>
Pendiente, %: (1-2) 2<br>
Términos municipales: Aldearrodrigo, Almenara de Tormes, Añover de Tormes, Doñinos de Ledesma, El Arco, Encina de San Silvestre, Gejuelo del Barro, Golpejas, Juzbado, La Mata de Ledesma, Ledesma, Monleras, Palacios del Arzobispo, Rollan, San Pedro del Valle, San Pelayo de Guareña, Sando, Santa Maria de Sando, Santiz, Sardon de los Frailes, Tabera de Abajo, Tremedal de Tormes, Valdelosa, Vega de Tirados, Villarmayor, Villasdardo, Villaseco de los Gamitos, Villaseco de los Reyes, Zamayon, Zarapicos.<br>
