Extensión, Km<sup>2</sup>: 4768<br>
Altitud, m: (626-997) 701<br>
Pendiente, %: (1-5) 3<br>
Términos municipales: Alcazar de San Juan, Arenas de San Juan, Argamasilla de Alba, Campo de Criptana, Damiel, Herencia, La Solana, Las Labores, Manzanares, Membrilla, Pedro Muñoz, Puerto Lapice, Ruidera, San Carlos del Valle, Santa Cruz de Mudela, Socuellamos, Tomelloso, Valdepeñas, Villarta de San Juan, Villarubia de los Ojos.<br>
