Extensión, Km<sup>2</sup>: 2983<br>
Altitud, m: (554-916) 689<br>
Pendiente, %: (1-11) 4<br>
Términos municipales: Alcolea de Calatrava, Aldea del Rey, Almagro, Argamasilla de Calatrava, Ballesteros de Calatrava, Bolaños de Calatrava, Cabezarados, Calzada de Calatrava, Caracuel de Calatrava, Carrion de Calatrava, Cañada de Calatrava, Ciudad Real, Corral de Calatrava, Fernancaballero, Granatula de Calatrava, Los Pozuelos de Calatrava, Miguelturra, Moral de Calatrava, Picon, Poblete, Pozuelo de Calatrava, Torralba de Calatrava, Valenzuela de Calatrava, Villamayor de Calatrava, Villar del Pozo.<br>
