Extensión, Km<sup>2</sup>: 1447<br>
Altitud, m: (0-721) 128<br>
Pendiente, %: (1-4) 2<br>
Términos municipales: Albatera, Algorfa, Almoradi, Benejuzar, Benferri, Benijofar, Bigastro, Callosa de Segura, Catral, Cox, Crevillente, Daya Nueva, Daya Vieja, Dolores, Elche / Elx, Formentera del Segura, Granja de Rocamora, Guardamar del Segura, Jacarilla, Los Montesinos, Orihuela, Pilar de la Horadada, Rafal, Redovan, Rojales, San Fulgencio, San Isidro, San Miguel de Salinas, Santa Pola, Torrevieja.<br>
