Extensión, Km<sup>2</sup>: 690<br>
Altitud, m: (0-459) 267<br>
Pendiente, %: (1-9) 5<br>
Términos municipales: Adsubia, Alcalali, Beniarbeig, Benichembla, Benidoleig, Benimeli, Benisa, Calp, Denia, El Poble Nou de Benitatxell, El Vergel, Els Poblets, Gata de Gorgos, Lliber, Murla, Ondara, Orba, Parcent, Pedreguer, Pego, Rafol de Almunia, Sagra, Sanet y Negrals, Senija, Teulada, Tormos, Vall de Ebo, Vall de Gallinera, Vall de Laguart, Xabia, Xalo.<br>
