Extensión, Km<sup>2</sup>: 798<br>
Altitud, m: (439-1008) 715<br>
Pendiente, %: (3-11) 7<br>
Términos municipales: Agres, Alcocer de Planes, Alcoi, Alcolecha, Alfafara, Almudaina, Balones, Benasau, Beniarda, Beniarres, Benifallin, Benifato, Benilloba, Benillup, Benimantell, Benimarfull, Benimassot, Castell de Castells, Cocentaina, Confrides, Facheca, Famorca, Gaianes, Gorga, Guadalest, I' Alqueria d'Asnar, I' Orxa, La Torre de les Maþanes, La Vall d'Alcala, Millena, Muro de Alcoy, Penaguila, Planes, Quatretondeta, Tollos.<br>
