Extensión, Km<sup>2</sup>: 3748<br>
Altitud, m: (61-714) 398<br>
Pendiente, %: (1-8) 4<br>
Términos municipales: Alanis, Almaden de la Plata, Aznalcollar, Castilblanco de los Arroyos, Cazalla de la Sierra, Constantina, El Castillo de las Guardas, El Garrobo, El Madroño, El Pedroso, El Real de la Jara, El Ronquillo, Gerena, Guadalcanal, Guillena, La Puebla de los Infantes, Las Navas de la Concepcion, San Nicolas del Puerto.<br>
