Extensión, Km<sup>2</sup>: 5398<br>
Altitud, m: (31-446) 142<br>
Pendiente, %: (1-4) 2<br>
Términos municipales: Alcala de Guadaira, Arahal, Carmona, Cañada Rosada, Ecija, El Coronil, El Cuervo de Sevilla, El Rubio, El Viso del Alcor, Fuentes de Andalucia, La Campana, La Lantejuela, La Luisiana, Las Cabezas de San Juan, Lebrija, Los Morales, Mairena del Alcor, Marchena, Osuna, Paradas, Utrera.<br>
