Extensión, Km<sup>2</sup>: 592<br>
Altitud, m: (51-106) 86<br>
Pendiente, %: (1-1) 1<br>
Términos municipales: Albaida del Aljarafe, Almensilla, Benacazon, Bollullos de la Mitacion, Bormujos, Carrion de los Cespedes, Castilleja de Guzman, Castilleja de la Cuesta, Castilleja del Campo, Espartinas, Gines, Huevar, Mairena del Aljarafe, Olivares, Pilas, Salteras, Sanlucar la Mayor, Tomares, Umbrete, Valencina de la Concepcion, Villanueva del Ariscal.<br>
