Extensión, Km<sup>2</sup>: 1565<br>
Altitud, m: (25-288) 96<br>
Pendiente, %: (1-3) 2<br>
Términos municipales: Alcala del Rio, Alcolea del Rio, Brenes, Burguillos, Camas, Cantillana, Coria del Rio, Dos Hermanas, Gelves, La Algaba, La Rinconada, Lora del Rio, Los Palacios y Villafranca, Palomares del Rio, Peñaflor, San Juan de Aznalfarache, Santiponce, Sevilla, Tocina, Villanueva del Rio y Minas, Villaverde del Rio.<br>
