<a href="../../../../soildesc/descrip.php3?prno=SE0502" target="_self">SE0502</a>&nbsp;
<a href="../../../../soildesc/descrip.php3?prno=SE0503" target="_self">SE0503</a>&nbsp;
<a href="../../../../soildesc/descrip.php3?prno=SE0504" target="_self">SE0504</a>&nbsp;
<a href="../../../../soildesc/descrip.php3?prno=SE0505" target="_self">SE0505</a>&nbsp;
<a href="../../../../soildesc/descrip.php3?prno=SE0506" target="_self">SE0506</a><br>
&nbsp;&nbsp;