Extensión, Km<sup>2</sup>: 1325<br>
Altitud, m: (307-1483) 768<br>
Pendiente, %: (1-12) 5<br>
Términos municipales: Ain, Alcudia de Veo, Algimia de Almonacid, Almedijar, Altura, Arañuel, Ayodar, Azuebar, Barracas, Bejis, Benafer, Castellnovo, Caudiel, Chovar, Cirat, El Toro, Eslida, Fuente la Reina, Fuentes de Ayodar, Gaibiel, Geldo, Higueras, Jerica, Matet, Montan, Montanejos, Navajas, Pavias, Pina de Montalgrao, Puebla de Arenoso, Sacañet, Segorbe, Soneja, Sot de Ferrer, Suera, Teresa, Toras, Torralba del Pinar, Torrechiva, Vall de Almonacid, Villamalur, Villanueva de Viver, Viver.<br>
