Extensión, Km<sup>2</sup>: 1030<br>
Altitud, m: (0-439) 178<br>
Pendiente, %: (1-11) 5<br>
Términos municipales: Alfondeguilla, Almassora, Almenara, Alquerias del Niño Perdido, Argelita, Artana, Benicassim, Betxi, Borriol, Burriana, Cabanes, Castello de la Plana, Chilches, Espadilla, Fanzara, La Llosa, La Vall d'Uixo, Moncofa, Nules, Onda, Oropesa, Ribesalbes, Tales, Toga, Torreblanca, Vallat, Vila-Real, Villavieja.<br>
