Cretácico: Calizas con Toucasias y Orbitolinas, margas, arenas, lutitas, areniscas, biocalcarenitas, lignitos, calizas, dolomías, calizas oolíticas, calizas laminadas y calizas con Characeas<br>
Neógeno: Lutitas rojas, areniscas y conglomerados<br>
Triásico: Dolomías, calizas margosas, margas, arcillas versicolores y yesos<br>
Cuaternario: Aluvial-coluvial, arcillas de descalcificación y marisma sin colmatar<br>
<br>
