Cretácico: Calizas, margas, calizas bioclásticas y arenosas, areniscas, arcillas, arenas, calizas con Orbitolinas, calizas con Toucasias, calizas oolíticas, calizas laminadas, calizas con Characeas y dolomías negras masivas<br>
Cuaternario: Glacis de cobertera antiguos, abanicos aluviales antiguos, glacis de cobertera, aluvial-coluvial, coluvión reciente y terrazas bajas<br>
Neógeno: Calizas, margas, lutitas, conglomerados y areniscas<br>
Jurásico: Calizas tableadas con nivel de areniscas en la base. Serie compresiva del Dogger<br>
<br>
