Cretácico: Calizas con Toucasias y Orbitolinas, calizas, margas, dolomías, calizas oolíticas, calizas laminadas, calizas con Characeas, arcillas, arenas, calizas bioclásticas y arenosas y areniscas<br>
Cuaternario: Glacis de cobertera, aluvial-coluvial y conos de deyección<br>
Neógeno: Conglomerados, areniscas, lutitas, calizas y margas<br>
Jurásico: Calizas tableadas con nivel de areniscas en la base. Serie compresiva del Dogger<br>
Paleógeno: Areniscas y grawacas<br>
<br>
<br>
