Cuaternario: Conglomerados, arcillas con cantos, mantos de arrollada, piedemonte, limos pardos y negros, albuferas, marismas e indiferenciado<br>
Triásico: Dolomías, margas, calizas, areniscas, limolitas rojas, arcillas y yesos<br>
Cretácico: Calizas con Toucasias y Orbitolinas, margas, calizas, dolomías, arenas, lutitas, areniscas, biocalcarenitas y lignitos<br>
Neógeno: Areniscas, lutitas y conglomerados <br>
<br>
