Extensión, Km<sup>2</sup>: 786<br>
Altitud, m: (384-654) 519<br>
Pendiente, %: (1-8) 4<br>
Términos municipales: Abelda de Iregua, Agoncillo, Albarite, Alcanadre, Arrubal, Ausejo, Clavijo, Corera, Daroca de Rioja, El Redal, Entrena, Fuenmayor, Galilea, Hornos de Moncavillo, Lagunilla del Jubera, Lardero, Leza de Rio Leza, Logroño, Medrano, Murillo de Rio Leza, Nalda, Navarrete, Ocon, Ribafrecha, Santa Engracia del Jubera, Sojuela, Sorzano, Sotes, Villamediana de Iregua.<br>
