Extensión, Km<sup>2</sup>: 806<br>
Altitud, m: (1045-1414) 1250<br>
Pendiente, %: (1-15) 7<br>
Términos municipales: Ajamil, Almarza de Cameros, Cabezon de Cameros, El Rasillo de Cameros, Gallinero de Cameros, Hornillos de Cameros, Jalon de Cameros, Laguna de Cameros, Lumbreras, Mancomunidad (Nalda, Sorzano, Viguera), Muro en Cameros, Nestares, Nieva de Cameros, Ortigosa de Cameros, Pinillos, Pradillo, Rabanera, San Roman de Cameros, Soto en Cameros, Terroba, Torre en Cameros, Torrecilla en Cameros, Viguera, Villanueva de Cameros, Villoslada de Cameros.<br>
