Extensión, Km<sup>2</sup>: 1302<br>
Altitud, m: (0-387) 157<br>
Pendiente, %: (1-12) 6<br>
Términos municipales: A Illa de Arousa, Baiona, Barro, Bueu, Caldas de Reis, Cambados, Cangas, Catoira, Gondomar, Marin, Meaño, Meis, Moaña, Moraña, Mos, Nigran, O Grove, O Porriño, Poio, Pontecesures, Pontevedra, Portas, Redondela, Ribadumia, Sanxenxo, Soutomaior, Valga, Vigo, Villaboa, Villagarcia de Arousa, Villanova de Arousa.<br>
