Silúrico: Esquistos, filitas, limolitas, grawacas, esquistos grafitosos, ampelitas y liditas<br>
Devónico: Esquistos, paragneises, metavulcanitas ácidas y esquistos albíticos<br>
Rocas graníticas hercínicas: Granitos de dos micas moderadamente leucocráticos y granitos de dos micas<br>
Rocas migmáticas: Metatexitas, diatexitas y granitoide inhomogéneo<br>
Precámbrico-Ordovícico: Esquistos, metagrawacas y paragneises<br>
<br>
