Extensión, Km<sup>2</sup>: 723<br>
Altitud, m: (0-300) 147<br>
Pendiente, %: (1-5) 3<br>
Términos municipales: Albons, Begur, Bellcaire d'Emporda, Calonge, Castell-Platja d'Aro, Colomers, Corþa, Cru´lles, Monells i Sant Sadurni de l'Heura, Foixa, Fontanilles, Forallac, Garrigoles, Gualta, Jafre, L'Escala, La Bisbal d'Emporda, La Pera, La Tallada d'Emporda, Montras, Palafrugell, Palamos, Palau-sator, Pals, Parlava, Regencos, Rupia, Sant Feliu de Guixols, Santa Cristina d'Aro, Serra de Daro, Torrent, Torroella de Montgri, Ulla, Ullastret, Ultramort, Vall-llobrega, Verges, Vilopriu.<br>
