Extensión, Km<sup>2</sup>: 737<br>
Altitud, m: (282-928) 579<br>
Pendiente, %: (2-14) 7<br>
Términos municipales: Argelaguer, Besali, Beuda, Castellfollit de la Roca, La Vall d'en Bas, La Vall de Bianya, Les Planes d'Hostoles, Les Preses, Maia de Montcal, Mieres, Montagut, Olot, Riudaura, Sales de llierca, Sant Aniol de Finistres, Sant Feliu de Pallerols, Sant Ferriol, Sant Jaume de Llierca, Sant Joan les Fonts, Santa Pau, Tortella.<br>
