Extensión, Km<sup>2</sup>: 1043<br>
Altitud, m: (0-1166) 393<br>
Pendiente, %: (1-13) 6<br>
Términos municipales: Amer, Angles, Arbuciles, Blanes, Breda, Brunyola, Caldes de Malavella, Espinelves, Hostalric, La Cellera de Ter, Lloret de Mar, Massanes, Maþanet de la Selva, Osor, Riells i Viabrea, Riudarenes, Riudellots de la Selva, Sant Andreu Salou, Sant Feliu de Buixalleu, Sant Hilari Sacalm, Sant Julia del Llor i Bonmati, Santa Coloma de Farners, Sils, Susqueda, Tossa de Mar, Vidreres, Viladrau, Vilobi d'Onyar.<br>
