Extensión, Km<sup>2</sup>: 838<br>
Altitud, m: (74-402) 181<br>
Pendiente, %: (1-7) 3<br>
Términos municipales: Aiguaviva, Banyoles, Bescano, Bordils, Camos, Campllong, Canet d'Adri, Cassa de la Selva, Celra, Cervia de Ter, Cornella del Terri, Crespia, Esponella, Flaþa, Fontcoberta, Fornells de la Selva, Girona, Julia, Llagostera, Llambilles, Madremanya, Palol de Revardit, Porqueres, Quart, Salt, Sanr Marti de Llemena, Sant Grgori, Sant Joan de Mollet, Sant Jordi Desvalls, Sant Julia de Ramis, Sant Marti Vell, Sant Miguel de de Campmajor, Sarria de Ter, Serinya, Vilablareix, Viladasens, Vilademuls.<br>
