Rocas plutónicas: Granodiorita biotítica de grano medio, granitos y leucogranitos biotíticos<br>
Neógeno: Arenas arcósicas, arcillas, conglomerados y areniscas<br>
Ordovícico: Micaesquistos, paragneises, esquistos y cuarcitas<br>
Cuaternario: Aluvial, terrazas fluviales, arcillas con cantos, conglomerados, cono de deyección antiguo, arenas y conglomerados cementados<br>
Paleozóico: Esquistos y metamórficos<br>
<br>
