Cuaternario: Indiferenciado, aluvial, terrazas fluviales, arcillas con cantos, conglomerados, dunas, arenas, limos eólicos y fangos salobres grises<br>
Ordovícico: Micaesquistos, paragneises, esquistos, cuarcitas, esquistos cuarzodeldespáticos, porfiroides, grawacas, pizarras azules y pizarras arcillosas negras con graptolites<br>
Paleógeno: Conglomerados, limolitas, margas, arcillas rojas, con niveles de areniscas y margas azules<br>
Rocas plutónicas: Granitos y leucogranitos biotíticos, granodiorita porfiroide y leucogranitos de dos micas<br>
<br>
