Rocas graníticas hercínicas: Granitoides inhomogéneos, granitos de dos micas, granodioritas, cuarzodioritas, dioritas y granitos biotíticos poscinemáticos<br>
Precámbrico-Devónico: Esquistos micáceos, grafitosos y cuarcíticos con algunas anfibolitas intercaladas, esquistos y paragneises metablásticos con paranfibolitas intercaladas<br>
Precámbrico-Ordovícico: Esquistos, metagrawacas, paragneises y metabasitas en facies anfibolita, localmente en facies granulita<br>
Cuaternario: Depósitos aluviales y fondos de vaguadas<br>
<br>
