Precámbrico-Ordovícico: Esquistos, metagrawacas, paragneises, metabasitas en facies anfibolita, localmente en facies granulita<br>
Silúrico: Pizarras, ampelitas, areniscas, esquistos, metavulcanitas, cuarcitas y filitas<br>
Rocas graníticas hercínicas: Granodioritas, granitos biotíticos precoces y gneises bandeados<br>
Rocas igneas: Granitoides de tendencia alcalina con deformación intensa<br>
<br>
