Extensión, Km<sup>2</sup>: 2390<br>
Altitud, m: (676-855) 765<br>
Pendiente, %: (1-3) 2<br>
Términos municipales: Belmonte, Carrascosa de Haro, Casas de Fernando Alonso, Casas de Haro, Casas de los Pinos, El Pedernoso, El Provencio, Fuentelespino de Haro, Hontanaya, La Alberca de Zancara, Las Mesas, Las Pedroñeras, Los Hinojosos, Monreal e Llano, Mota del Cuervo, Osa de la Vega, Pozoamargo, Rada de Haro, San Clemente, Santa Maria de los Llanos, Santa Maria del Campo Rus, Tresjuncos, Vara de Rey, Villaescusa de Haro, Villamayor de Santiago, Villar de la Encina.<br>
