Extensión, Km<sup>2</sup>: 2141<br>
Altitud, m: (602-1000) 815<br>
Pendiente, %: (1-3) 2<br>
Términos municipales: Alarcon, Buenache de Alarcon, Campillo de Altobuey, Casas de Benitez, Casas de Guijaro, Casasimarro, Castillejo de Iniesta, El Herrumblar, El Peral, El Picazo, Gabaldon, Graja de Iniesta, Hontecillas, Iniesta, Ledaña, Minglanilla, Motilla del Palancar, Olmdilla de Alarcon, Pozorrubielos de la Mancha, Puebla de Salvador, Qunitanar del Rey, Sisante, Tebar, Valhermoso de la Fuente, Valverdejo, Villagarcia del Llano, Villalpardo, Villanueva de la Jara, Villarta.<br>
