Extensión, Km<sup>2</sup>: 3298<br>
Altitud, m: (692-1604) 1077<br>
Pendiente, %: (1-9) 5<br>
Términos municipales: Abia de la Obispalia, Albadalejo del Cuende, Almodovar del Pinar, Arcas del Villar, Arcos de la Sierra, Barchin del Hoyo, Bascuñana de San Pedro, Beamud, Buenache de la Sierra, Castillejo-Sierra, Cañamares, Chillaron de Cuenca, Chumillas, Cuenca, Enguidamos, Fresnada de la Sierra, Fresneda de Altarejos, Fuentenava de Jabaga, Fuentes, La Cierva, La Frontera, La Parra de las Vegas, La Pesquera, Las Valeras, Mariana, Monteagudo de las Salinas, Olmeda del Rey, Olmeda del Rey, Palomera, Paracuellos, Piqueras del Castillo, Portilla, Solera de Gabatdon, Sotorribas, Uña, Valdemorillo de la Sierra, Valdemoro-Sierra, Valdetortola, Villalba de la Sierra, Villar de Olalla, Zarzuela.<br>
