Extensión, Km<sup>2</sup>: 2519<br>
Altitud, m: (798-1360) 1088<br>
Pendiente, %: (1-7) 4<br>
Términos municipales: Alcala de la Vega, Algarra, Aliaguilla, Arguisuelas, Boniche, Campillo-Paravientos, Campillos-Sierra, Carboneras de Guadazaon, Cardenete, Casas de Garcimolina, Cañada del Hoyo, Cañete, Fuentelespino de Moya, Garaballa, Graja de Campalbo, Henarejos, Huerguina, Landete, Mira, Moya, Narboneta, Pajaron, Pajaroncillo, Reillo, Salinas del Manzano, Salvacañete, San Martin de Boniches, Santa Cruz de Moya, Talayuelas, Tejadillos, Villar del Humo, Villora, Yemeda.<br>
