Extensión, Km<sup>2</sup>: 2256<br>
Altitud, m: (651-1016) 876<br>
Pendiente, %: (1-7) 4<br>
Términos municipales: Albalate de Nogueras, Albendea, Alcantud, Alcohujate, Arandilla del Arroyo, Arrancacepas, Barajas de Melo, Buciegas, Buendia, Canalejas del Arroyo, Castejon, Castillo-Albarañez, Cañaveras, Cañaveruelas, Gascueña, Huete, La Peraleja, Leganiel, Los Valdecolmenas, Olmeda de la Cuesta, Olmedilla de Eliz, Pineda de Cigüela, Portalrubio de Guadamejud, Priego, Puebla de Don Francisco, Saceda-Trasierra, Salmeorcillos, San Pedro Palmiches, Tinajas, Torralba, Valdeolivas, Vellisca, Villaconejos de Trabaque, Villalba del Rey, Villanueva de Guadamjud, Villar de Domingo Garcia, Villar del Infantado, Villar y Velasco, Villarejo de la Peñuela, Villas de la Ventosa, Vindel.<br>
