Cretácico: Calizas, dolomías, margas, yesos, arcillas y calizas dolomíticas<br>
Paleógeno: Conglomerados, areniscas, margas, calizas y yesos<br>
Neógeno: Conglomerados, areniscas, margas, arcillas e indiferenciado<br>
Jurásico: Calizas, dolomías, areniscas, margas, calizas oolíticas, calizas con silex, calizas margosas, brechas y calizas dolomíticas<br>
Triásico: Conglomerados, areniscas, lutitas, dolomías, arcillas y yesos<br>
<br>
