Cretácico: Calizas dolomíticas, dolomías, calizas, margas, arcillas verdes en la base, areniscas, arenas blancas y amarillentas y arcillas<br>
Jurásico: Brechas, dolomías, calizas, calizas oolíticas, calizas con silex y calizas margosas<br>
Triásico: Conglomerados, areniscas, limolitas, arcillas abigarradas, yesos, dolomías, calizas y margas<br>
Neógeno: Arcillas pardas, areniscas, conglomerados, lutitas, calizas travertínicas y margas<br>
Cuaternario: Glacis y mantos de arrollada<br>
<br>
