Extensión, Km<sup>2</sup>: 1910<br>
Altitud, m: (671-1990) 1192<br>
Pendiente, %: (1-12) 6<br>
Términos municipales: Albuñan, Aldeire, Alicun de Ortega, Alquiefe, Beas de Guadix, Benalua de Guadix, Cogollos de Guadix, Cortes y Graena, Darro, Dehesas de Guadix, Diezma, Dolar, Ferreira, Fonelas, Freila, Gor, Gorafe, Guadix, Huelago, Hueneja, Jerez del Marquesado, La Calahorra, La Peza, Lanteira, Lugros, Marchal, Policar, Purullena, Valle del Zabali, Villanueva de las Torres.<br>
