Extensión, Km<sup>2</sup>: 2008<br>
Altitud, m: (500-2830) 1071<br>
Pendiente, %: (1-17) 8<br>
Términos municipales: Albolote, Alfacar, Alhendin, Armilla, Atarfe, Beas de Granada, Cajar, Calicasas, Cenes de la Vega, Chauchina, Churriana de la Vega, Cijuela, Cogollos Vega, Cullar-Vega, Dilar, Dudar, Fuente Vaqueros, Gojar, Granada, Güejar-Sierra, Güevejar, Huetor-Santillan, Huetor-Tajar, Huetor-Vega, Jun, La Zubia, Lachar, Las Gabias, Loja, Maracena, Monachil, Moraleda de Zafayona, Nivar, Ogijares, Otura, Peligros, Pinos-Genil, Pinos-Puente, Pulianas, Quentar, Salar, Santa Fe, Vegas del Genil, Villanueva Mesias, Viznar, Zagra.<br>
