Extensión, Km<sup>2</sup>: 1302<br>
Altitud, m: (376-923) 548<br>
Pendiente, %: (1-8) 4<br>
Términos municipales: Aibar, Artajona, Barasoain, Beire, Berbinzana, Caseda, Eslava, Ezprogui, Facero de Ujue y Lerga, Gallipienzo, Garinoain, Javier, Larraga, Leache, Leoz, Lerga, Liedana, Mendigorria, Olite, Oloriz, Orisoain, Petilla de Aragon, Pitillas, Pueyo, Sada, San Martin de Unx, Sangüesa, Tafalla, Ujue, Unzue, Yesa.<br>
