Extensión, Km<sup>2</sup>: 2313<br>
Altitud, m: (406-1590) 894<br>
Pendiente, %: (1-12) 6<br>
Términos municipales: Abaurregaina/Abaurrea Alta, Abaurrepea/Abaurrea Baja, Aoiz/Agoitz, Arce, Aria, Aribe, Auritz/Burguete, Burgui, Castillo-Nuevo, Erro, Esparza de Salazar, Esteribar, Ezcaroz, Gallues, Garaioa, Garde, Garralda, Güesa, Hiriberri/Villanueva de Aezkoa, Ibargoiti, Isaba, Izagaonda, Izalzu, Jaurrieta, Jaurrieta y Elcoaz, Lizoain, Longuida, Lumbier, Luzarde/Valcarlos, Monreal, Navascues, Ochagavia, Orbaitzeta, Orbara, Oronz, Oroz-Betelu, Orreaga/Roncesvalles, Romanzado, Roncal, Sarries, Unciti, Urraul Alto, Urraul Bajo, Urroz, Urzainqui, Uztarroz, Vidangoz.<br>
