Extensión, Km<sup>2</sup>: 1899<br>
Altitud, m: (100-981) 586<br>
Pendiente, %: (1-21) 8<br>
Términos municipales: Altsasu/Alsasua, Anue, Araitz, Arakil, Arano, Arantza, Arbizu, Areso, Arruazu, Atez, Bakaiku, Basaburua, Baztan, Beintza-Labaien, Bera/Vera de Bidasoa, Bertizarana, Betelu, Donamaria, Doneztebe-Santesteban, Elgorriaga, Eratsun, Ergoiena, Etxalar, Etxarri-Aranatz, Ezcabarte, Ezkurra, Goizueta, Igantzi, Imotz, Irañeta, Irurtzun, Ituren, Iturmendi, Lakuntza, Lantz, Larraun, Leitza, Lekunberri, Lesaka, Mancomunidad de Beunza y Buarbe, Mancomunidad de Uharte-Arakil e Irañeta, Odieta, Oitz, Olaibar, Olatzi/Olazagutia, Saldias, Sunbilla, Uharte-Arakil, Ultzama, Union de los Montes de Aralar, Urdazubi/Urdax, Urdiain, Urrotz, Ziordia, Zubieta, Zugarramundi.<br>
