Extensión, Km<sup>2</sup>: 777<br>
Altitud, m: (398-914) 561<br>
Pendiente, %: (1-9) 5<br>
Términos municipales: Adios, Ansoain, Aranguren, Artazu, Añorbe, Barañain, Belascoain, Beriain, Berrioplano, Berriozar, Biurrun-Olcoz, Burlada, Ciriza, Cizur, Echarri, Egües, Eneriz, Etxauri, Faceria de Ezcabarte y otros, Galar, Goñi, Guirguillano, Huarte/Uharte, Iza, Juslapeña, Legarda, Murruzabal, Obanos, Ollo, Olza, Orcoyen, Pamplona, Puente la Reina/Gares, Tiebas-Muruarte de Reta, Tirapu, Ucar, Uterga, Valle de Elorz, Vidaurreta, Villava/Atarrabia, Zabalza, Zizur Mayor/Zizur Nagusia.<br>
