Extensión, Km<sup>2</sup>: 2671<br>
Altitud, m: (303-1365) 774<br>
Pendiente, %: (1-10) 6<br>
Términos municipales: Baltar, Bande, Baños de Molgas, Calvos de Randin, Castrelo do Val, Cualedro, Entrimo, Laza, Lobeira, Lobios, Maceda, Monterrei, Muiños, Oimbra, Os Blancos, Porqueira, Rairiz de Veiga, Rios, Sandias, Sarreaus, Trasmiras, Verea, Verin, Vilar de Barrio, Vilar de Santos, Vilardevos, Xinzo de Limia, Xunqueira de Ambia.<br>
