Extensión, Km<sup>2</sup>: 2465<br>
Altitud, m: (283-1705) 961<br>
Pendiente, %: (1-15) 7<br>
Términos municipales: A Gudiña, A Mezquita, A Pobra de Trives, A Rua, A Teixeira, A Veiga, Carballeda de Valdeorras, Castro Caldelas, Chandexa de Queixa, Manzaneda, Montederramo, O Barco de Valdeorras, O Bolo, Parada de Sil, Petin, Rubia, San Xoan de Rio, Viana do Boto, Vilariño de Conso, Villamartin de Valdeorras, larouco.<br>
