Extensión, Km<sup>2</sup>: 2157<br>
Altitud, m: (91-1014) 482<br>
Pendiente, %: (1-9) 5<br>
Términos municipales: A Arnoia, A Bola, A Merca, A Peroxa, Allariz, Amoeiro, Avion, Barbadas, Beade, Beariz, Boboras, Carballeda de Avia, Cartelle, Castrelo de Miño, Celanova, Cenlle, Coles, Cortegada, Esgos, Gomesende, Leiro, Maside, Melon, Nogueira de Ramuin, O Carballiño, O Irixo, O Pereiro de Aguilar, Ourense, Paderne de Allariz, Padrenda, Piñor, Pontedeva, Punxin, Quintela de Leirado, Ramiras, Ribadavia, San Amaro, San Cibrao das Viñas, San Cristovo de Cea, Taboadela, Toen, Vilamarin, Xunqueira de Espadanedo.<br>
