Rocas graníticas hercínicas: Granitos de dos micas moderadamente leucocráticos, granitoide inhomogéneo, granitos biotíticos y granodioritas biotítico-anfibólicas con zonas de grano medio y grueso<br>
Silúrico: Esquistos, filitas, limolitas, grawacas, esquistos grafitosos, ampelitas y liditas<br>
Cuaternario: Abanicos aluviales. Arenas, arcillas y cantos. Depósitos palustres. Limos, turbas, arcillas y limos. Aluvial. Canales meadriformes y llanura de inundación<br>
Precámbrico-Ordovícico: Esquistos, esquistos feldespáticos, paragneises, metavulcanitas, esquistos micáceos y andalucíticos <br>
<br>
