Rocas graníticas hercínicas: Granitos de dos micas moderadamente leucocráticos, granitos biotíticos y granodioritas biotítico-anfibólicos y granitos de dos micas muy leucocráticos<br>
Silúrico: Esquistos, filitas. limolitas, grawacas, esquistos grafitosos, ampelitas y liditas<br>
Precámbrico-Ordovícico: Esquistos, esquistos feldespáticos, paragneises y metavulcanitas<br>
Devónico: Metavulcanitas ácidas<br>
<br>
<br>
