Extensión, Km<sup>2</sup>: 1927<br>
Altitud, m: (900-1296) 1053<br>
Pendiente, %: (1-3) 2<br>
Términos municipales: Alcubilla de Avellaneda, Burgo de Osma-Ciudad de Osma, Caracena, Carrascosa de Abajo, Castillejo de Robledo, Espeja de San Marcelino, Espejon, Fresno de Caracena, Fuentearmegil, Fuentecambron, Herrera de Soria, Ucero y Nafria de Ucero, Langa de Duero, Liceras, Miño de San Esteban, Montejo de Tiermes, Nafria de Ucero, Recuerda, Retortillo de Soria, San Esteban de Gormaz, Santa Maria de las Hoyas, Ucero, Valdemaluque, Villanueva de Gormaz.<br>
