Extensión, Km<sup>2</sup>: 1304<br>
Altitud, m: (900-1198) 1052<br>
Pendiente, %: (1-4) 3<br>
Términos municipales: Adradas, Alentisque, Almazan, Arenillas, Barca, Barcones, Berlanga de Duero, Borjabad, Caltojar, Centenera de Andaluz, Coscurita, Escobosa de Almazan, Frechilla de Almazan, La Riba de Escalote, Majan, Matamala de Almazan, Momblona, Moron de Almazan, Nepas, Nolay, Rello, Soliedra, Taroda, Velamazan, Viana de Duero.<br>
