Extensión, Km<sup>2</sup>: 1278<br>
Altitud, m: (915-1955) 1274<br>
Pendiente, %: (1-11) 5<br>
Términos municipales: Aldealices, Almarza, Arevalo de la Sierra, Ausejo de la Sierra, Carrascosa de la Sierra, Castrilfrio de la Sierra, Cerbon, Cigudosa, El Royo, Estepa de San Juan, Fuentes de magaña, Fuentestrun, La Poveda de Soria, Las Aldehuetas, Magaña, Oncala, Rebollar, Rollamienta, San Felices, San Pedro Manrique, Santa Cruz de Yanguas, Sotilla del Rincon, Suellacabras, Trevago, Valdeavellano de Tera, Valdegeña, Valdelagua del Cerro, Valdeprado, Valtajeros, Villar del Ala, Villar del Rio, Vizmanos, Yanguas.<br>
