Extensión, Km<sup>2</sup>: 1728<br>
Altitud, m: (0-533) 159<br>
Pendiente, %: (1-12) 5<br>
Términos municipales: Alfoz de Lloredo, Ampuerto, Argoños, Arnuero, Barcena de Cicero, Bareyo, Cabezon de la Sal, Camargo, Cartes, Castañeda, Castro-Urdiales, Colindres, Comillas, El Astillero, Entrambasaguas, Escalante, Guriezo, Hazas de Cesto, Herrerias, Laredo, Liendo, Lierganes, Limpias, Marina de Cudeyo, Mazcuerras, Medio Cudeyo, Meruelo, Miengo, Noja, Penagos, Pielagos, Polanco, Puente de Viesgo, Reocin, Ribamontan al Mar, Ribamontan al Monte, Riotuerto, Ruiloba, San Vicente de Barquera, Santa Cruz de Bezana, Santa Maria de Cayon, Santander, Santillana del Mar, Santoña, Solorzano, Suances, Torrelavega, Udias, Val de San Vicente, Valdaliga, Villaescusa, Voto.<br>
