Extensión, Km<sup>2</sup>: 1159<br>
Altitud, m: (354-2086) 930<br>
Pendiente, %: (1-22) 8<br>
Términos municipales: Arenas de San Pedro, Candeleda, Candeleda (Reserva Nacional de Gredos), Casavieja, Casillas, Cuevas del Valle, El Arenal, El Hornillo, El Hornillo (Reserva Nacional de Gredos), Fresnedilla, Gavilanes, Guisando, Guisando (Reserva Nacional de Gredos), Higuera de las Dueñas, La Adrada, Lanzahita, Mijares, Mombeltran, Mombeltran, Mombeltran, Mombeltran, Navahondilla, Pedro Bernardo, Piedralaves, Poyales del Hoyo, San Esteban del Valle, Santa Cruz del Valle, Santa Maria del Tietar, Sotillo de la Adrada, Villarejo del Valle.<br>
