Extensión, Km<sup>2</sup>: 936<br>
Altitud, m: (788-979) 860<br>
Pendiente, %: (1-2) 2<br>
Términos municipales: Bercianos del Real Camino, Calzada del Coto, Castrotierra de Valmadrigal, Cea, El Burgo Ranero, Escobar de Campos, Gordaliza del Pino, Grajal de Campos, Joarilla de las Matas, Sahagun, Santa Maria del Monte de Cea, Santa Maria del Monte de Cea, Villamol y Villaselan, Santa Maria del Monte de Cea, Villamol y Villaselan, Vallecillo, Villamol, Villaselan, Villazanzo de Valderaduey.<br>
