Extensión, Km<sup>2</sup>: 654<br>
Altitud, m: (784-1000) 863<br>
Pendiente, %: (1-2) 2<br>
Términos municipales: Alija del Infantado, Castrillo de la Valduema, Castrocalbon, Cebrones del Rio, Destriana, La Bañeza, Palacios de la Valduema, Quintana del Marco, Quintana y Congosto, Regueras de Arriba, Riego de la Vega, Riego de la Vega y Villamontan de la Valduema, San Cristobal de la Polantera, San Esteban de Nogales, Santa Elena de Jamuz, Santa Maria de la Isla, Soto de la Vega, Soto de la Vega y Villazala, Villamontan de la Valduema.<br>
