Extensión, Km<sup>2</sup>: 2409<br>
Altitud, m: (894-2014) 1341<br>
Pendiente, %: (1-14) 7<br>
Términos municipales: Acebedo, Boca de Huernago, Boñar, Buron, Carmenes, Cistierna, Cremenes, La Encina, La Vecilla, Maraña, Matallana, Oseja de Sajambre, Pedrosa del Rey, Posada de Valdeon, Prioro, Puebla de Lillo, Reyero, Riaño, Sabero, Valdelugueros, Valdepielago, Valderrueda, Vegacervera, Vegaquemada.<br>
