Extensión, Km<sup>2</sup>: 1398<br>
Altitud, m: (847-1408) 1040<br>
Pendiente, %: (1-5) 3<br>
Términos municipales: Astorga, Bazuelo, Benavides, Carrizo, Hospital de Orbigo, Las Omañas, Llamas de la Ribera, Magaz de Cepda, Quintana del Castillo, Quintana del Castillo y Villagaton, San Justo de la Vega, Santa Colomba de Somoza, Santiago Millas, Turcia, Val de San Lorenzo, Valderrey, Valdesamario, Villagaton, Villamejil, Villaobispo de Otero, Villarejo de Orbigo, Villares de Orbigo.<br>
