Extensión, Km<sup>2</sup>: 2828<br>
Altitud, m: (497-1798) 931<br>
Pendiente, %: (1-19) 7<br>
Términos municipales: Arganza, Balboa, Barjas, Bembibre, Berlanga del Bierzo, Borrenes, Cabañas Raras, Cacabelos, Camponaraya, Candin, Carracedelo, Carucedo, Castropodame, Congosto, Corullon, Cubilos de Sil, Fabero, Folgoso de la Ribera, Igüeña, Molinaseca, Noceda, Oencia, Paramo del Sil, Peranzanes, Ponferrada, Priaranza del Bierzo, Puente de Domingo Florez, Sancedo, Sobrado, Toreno, Torre del Bierzo, Trabadelo, Vega de Espinareda, Vega de Valcarce, Villadecanes, Villafranca del Bierzo.<br>
