Extensión, Km<sup>2</sup>: 895<br>
Altitud, m: (750-879) 811<br>
Pendiente, %: (1-1) 1<br>
Términos municipales: Ardon, Bercianos del Paramo, Bustillo del Paramo, Chozas de Abajo, La Antigua, Laguna Dalga, Laguna de Negrillos, Pobladura de Pelayo Garcia, Pozuelo del Paramo, Roperuelos del Paramo, San Adrian del Valle, San Pedro Bercianos, Santa Maria del Paramo, Santa Marina del Rey, Urdiales del Paramo, Valdefuentes del Paramo, Valdevimbre, Villadangos del Paramo, Villazala, Zotes del Paramo.<br>
