Extensión, Km<sup>2</sup>: 1753<br>
Altitud, m: (856-1155) 966<br>
Pendiente, %: (1-4) 3<br>
Términos municipales: Almanza, Cebanico, Cimanes del Tejar, Cuadro, Cubillas de Rueda, Garrafe de Torio, Gradefes, Leon, Prado de Guzpeña, Rioseco de Tapia, San Andres de Rabanedo, Santa Columba de Curueño, Santa Maria de Ordas, Santovenia de la Valdoncina, Sariegos, Valdefresno, Valdepolo, Valverde de la Virgen, Vegas del Condado, Villamartin de Don Sancho, Villaquilambre.<br>
